### ISSUE TITLE
Task progress bar in the task list

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#835] opened 2020-01-27 19:47 UTC
### Steps to reproduce

1. Create a new task.
2. Set the task completion to e.g. 30%.
3. Save the task.

### Expected behaviour
The task progress bar on the task list should be of sufficient length to complete the task.

### Actual behaviour
The task progress bar on the task list is 100% long.

![obraz](https://user-images.githubusercontent.com/47037905/73208132-34593880-4146-11ea-9c82-b0e04035ccf0.png)

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Tasks version:** (see Nextcloud apps page)
0.11.3

### Client configuration
**Browser:**
Firefox 72.0.2

**Operating system:**
Win7

**Comment by raimund-schluessler** [comment] 2020-01-27 19:58
Hm, I cannot reproduce this:

![Screenshot_2020-01-27 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/73209036-c150c180-4147-11ea-8c55-5b2eca7dd993.png)


Could it be, that the calendar color is not visible (gray)?

**Comment by Valdnet** [comment] 2020-01-27 20:07
> Could it be, that the calendar color is not visible (gray)?

@raimund-schluessler Yes. It turns out to be invisible.

**Comment by raimund-schluessler** [comment] 2020-01-27 20:21
I guess this is not a bug, then.

**Comment by Valdnet** [comment] 2020-01-27 20:37
What could be the reason? Nextcloud color themes I have set to blue if it has something in common.

**Comment by raimund-schluessler** [comment] 2020-01-27 20:45
Well, you chose a calendar color that is not visible on gray. You can change it in the left sidebar, selecting the calendar in question and chosing "edit" in the three-dot dropdown menu.

**Comment by Valdnet** [comment] 2020-01-27 21:00
That's right I didn't have the calendar color selected.

@raimund-schluessler Don't you think it is a bit strange that if the calendar has no color selected then the progress bar is not visible? The progress bar should in this case take the color of themes Nextcloud.

**Comment by raimund-schluessler** [comment] 2020-01-27 21:07
It is already strange, that no color was selected. Did you newly create this calendar or was it from a previous installation?

I don't really know how to detect if no color is available. Since by default a calendar always has a color it is hard for me to reproduce this. But ofc, in this case the default color should be shown.

**Comment by Valdnet** [comment] 2020-01-27 22:05
> It is already strange, that no color was selected. Did you newly create this calendar or was it from a previous installation?

I created a new calendar and I have no idea how it happened that he had no color assigned.

**Comment by raimund-schluessler** [comment] 2020-01-28 07:52
> I created a new calendar and I have no idea how it happened that he had no color assigned.

Is this reproducible? If so, could you tell me which background-color is assigned to the progressbar (this element: `<div class="percentdone" style="width: 19%; background-color: rgb(255, 41, 104);"></div>`).

**Comment by raimund-schluessler** [comment] 2020-01-28 07:55
It might be enough to add `background-color: $color-primary;` here https://github.com/nextcloud/tasks/blob/master/css/src/style.scss#L536 (and unrelated, remove the `opacity: .75;`)

**Comment by Valdnet** [comment] 2020-01-28 09:26
It seems to me that this happens when creating the first list on a clean instance.

This `<div class="percentdone" style="width: 19%; background-color: rgb(255, 41, 104);"></div> `element is not present.

On the first list, where the color cannot be seen, is `<div class="app-navigation-entry-bullet"></div>`.

At the second list, `<div class="app-navigation-entry-bullet" style="background-color: rgb(0, 0, 201);"></div>` is already defined.

![obraz](https://user-images.githubusercontent.com/47037905/73250575-648cef80-41b7-11ea-80d2-112c973df97e.png)

**Comment by raimund-schluessler** [comment] 2020-01-28 09:41
The `percentdone` is in the task list, it is the progress bar element, but it is only present if a task with a progress > 0 is visible.

It seems that the calendar-color really is empty, could you please report a separate bug for this? With the exact steps how to reproduce it.

**Comment by Valdnet** [comment] 2020-01-28 10:16
> The percentdone is in the task list, it is the progress bar element, but it is only present if a task with a progress > 0 is visible.

Ahhhh... It looks like the color is also not configured in `percentdone`.
`<div aria-label="Ukończono 21 %" class="percentdone" style="width: 21%;"></div>`

![obraz](https://user-images.githubusercontent.com/47037905/73254834-71154600-41bf-11ea-8c00-5b41dea96494.png)

**Comment by raimund-schluessler** [comment] 2020-01-28 10:30
Then https://github.com/nextcloud/tasks/issues/835#issuecomment-579123623 would solve this specific issue, I will create a PR. But the actual question still is why this calendar has no color assigned.

**Comment by Valdnet** [comment] 2020-01-28 10:51
@raimund-schluessler I have already created the issue and described the steps #838 of how it arises.
This issue can be closed.

Thank you for your patience 😉.

**Closed** 2020-01-28 11:00 UTC
