### ISSUE TITLE
Export tasks to CSV

### ISSUE THREAD

**Issue by dzidek23** [nextcloud/tasks#2322] opened 2023-08-24 09:25 UTC
I know this has been requested in many forms before but yet again, I'd like to ask for an easy way to export to CSV.

At the moment, using the .ics file there's no simple way to print a complete list of tasks. One has to do some magic awk on a commandline to get it converted. CSV export would be a great improvement.

Also, I was looking at the Nextcloud database to see if I can pull the data directly from there but I can't find any reference to Tasks.

**Comment by raimund-schluessler** [comment] 2023-08-24 09:35
Duplicate of https://github.com/nextcloud/tasks/issues/163.

**Closed by raimund-schluessler** 2023-08-24 09:35 UTC
