### ISSUE TITLE
Show details view after adding task

### ISSUE THREAD

**Issue by treiher** [nextcloud/tasks#463] opened 2019-06-25 16:12 UTC
### Steps to reproduce
Add a task

### Expected behaviour
The task is added to the task list and the details view is shown for adding further details. (This was the behaviour before upgrading to version 0.10.)

### Actual behaviour
The task is added to the task list, but one has to search the task and click on it to add further details.

### Server configuration

**Nextcloud version:** 15.0.8

**Tasks version:** 0.10.1

**Comment by raimund-schluessler** [comment] 2019-06-25 20:17
Duplicate of #397, will be released with v0.11.0.

**Closed by raimund-schluessler** 2019-06-25 20:17 UTC
