### ISSUE TITLE
Tasks in a Shared calendar do not display when shared by group.

### ISSUE THREAD

**Issue by phetish** [nextcloud/tasks#85] opened 2017-06-06 00:28 UTC
### Steps to reproduce
1. Add user to a group. 
2.  Create a calendar 
3.  Share Calendar to the above group.
4. In Tasks app, the shared calendar does not appear.
5. Go back to calendar and share with the same user.
6. Shared calendar and tasks now appear in the Tasks App.

### Expected behaviour
Sharing by group should include all users of group.

### Actual behaviour
See the "Steps to Reproduce" listed above

### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
NextCloud 12

**Tasks version:** (see Nextcloud apps page)
0.9.5

**Updated from an older Nextcloud or fresh install:**
Update from 11.x

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
Enabled:
  - activity: 2.5.2
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 5.0.0
  - richdocuments: 1.12.31
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - weather: 1.4.2
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - issuetemplate
  - mail
  - registration
  - user_external
  - user_ldap

```

**Are you using external storage, if yes which one:**
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome Version 58.0.3029.110 (64-bit)

**Operating system:**
Win10

**CalDAV-clients:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by swissbyte** [comment] 2017-11-14 19:38
Same problem here

Vote Up

**Comment by Henry-White** [comment] 2018-11-28 08:34
The same problem. Up.

**Comment by ssoftS** [comment] 2018-12-12 23:07
I have the same problem with 14.0.4 !
Please solve this, it's not "Groupware" worthy.

Thanks.

**Comment by raimund-schluessler** [comment] 2018-12-13 09:57
Does the calendar shared by group appear correctly in the Calendar app?

**Comment by ssoftS** [comment] 2018-12-13 16:59
The shared calendar from Calendar-App will be correct view in Task-App.
But when i create a task with a date, is this event (task) not show in Calendar-App.

**Comment by raimund-schluessler** [comment] 2018-12-13 17:13
> The shared calendar from Calendar-App will be correct view in Task-App.
> But when i create a task with a date, is this event (task) not show in Calendar-App.

Sorry, but that is a completely different issue. Actually not a bug, but simply not implemented. Also, this has to be implemented in the Calendar app, see https://github.com/nextcloud/calendar/issues/28

Could one of the others report on the actual issue, please.

**Comment by raimund-schluessler** [comment] 2019-05-13 08:16
Could you please check if this is still an issue with v0.10.1?

**Comment by raimund-schluessler** [comment] 2019-05-17 11:57
A calendar / task list shared with a group is shown for every member of this group with Tasks v0.10.1 (probably working before already, but that's the version I tested).

Since there is no more feedback and the bug seems to be solved I close this issue.

**Closed by raimund-schluessler** 2019-05-17 11:57 UTC
Labels: bug
