### ISSUE TITLE
Unsaved changes override other task

### ISSUE THREAD

**Issue by googol42** [nextcloud/tasks#453] opened 2019-06-16 11:39 UTC
Maybe this is a duplicate to #403.

### Steps to reproduce
1. Create the tasks "task1" and "task2"
2. Open "task1" and enter a description. Make sure the description is saved
3. Open "task2" and click the description field (-> cursor visible) but don't enter anything.
4. Open "task1"

### Expected behaviour
"task1" should contain the description entered in step 1.

### Actual behaviour
The description was overridden be an empty string.

It seems that everything you change in "task1" and is not sync with the server (priority, due/start date, description, % completion) is overriding the values in "task2" when you open it.

## Server configuration detail

**Operating system:** Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64

**Webserver:** Apache/2.4.39 (Unix) (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 

7.1.30
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, restrictdocroot, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, apcu, gnupg, imagick, zip, phalcon, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - audioplayer: 2.7.0
 - calendar: 1.7.0
 - camerarawpreviews: 0.7.0
 - checksum: 0.4.3
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - gallery: 18.3.0
 - gpxpod: 3.0.3
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - previewgenerator: 2.1.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - tasks: 0.10.1
 - twofactor_backupcodes: 1.5.0
 - unsplash: 1.1.3
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - phonetrack
 - support
 - survey_client
 - systemtags
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "theme": "",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by raimund-schluessler** [comment] 2019-06-16 17:41
Yes, duplicate of #404 and #449 and fixed with #405. Will be released with v0.11.0.

**Closed by raimund-schluessler** 2019-06-16 17:41 UTC
