### ISSUE TITLE
adding a list of tasks at once

### ISSUE THREAD

**Issue by brahimjarallah** [nextcloud/tasks#2344] opened 2023-09-19 09:12 UTC
### Steps to reproduce
possibility of adding a list of tasks at once

### Expected behaviour
when we add new task only one task is permitted however it's better to copy from clipboard a list of tasks to the task app without the headache of adding them one by one

**Comment by raimund-schluessler** [comment] 2023-09-19 09:24
Duplicate of #1894. This feature was recently implemented in #2273 and will be released with v0.16.0.

**Closed by raimund-schluessler** 2023-09-19 09:24 UTC
