### ISSUE TITLE
Calendar cut off on the left side

### ISSUE THREAD

**Issue by christian-roeser** [nextcloud/tasks#1407] opened 2021-01-30 22:00 UTC
### Steps to reproduce
1. Create a new task
2. Pick a date from the calendar

### Expected behaviour
You should see the whole calendar

### Actual behaviour
The left side of the calendar ist missing
![image](https://user-images.githubusercontent.com/78270584/106368761-78c87700-634c-11eb-8f78-8c326b7f2300.png)

### Server configuration

**Web server:**
Apache (apache2handler)

**PHP version:**
7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, apcu, imagick, memcached, redis, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
20.0.6 - 20.0.6.1

**Tasks version:** (see Nextcloud apps page)
tasks: 0.13.6

**Updated from an older Nextcloud or fresh install:**
Fresh install of 20.0.3 and update to 20.6.1

### Client configuration
**Browser:**
Microsoft Edge and Chrome

**Operating system:**
Windows 10

**Comment by raimund-schluessler** [comment] 2021-01-31 07:02
Duplicate of #935.

**Closed by raimund-schluessler** 2021-01-31 07:02 UTC
