### ISSUE TITLE
Tasks Design improvements

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1665] opened 2021-06-29 12:39 UTC
Hey, I've lately though about the tasks design and ideas how it could be further improved.

## Desktop
| Before | After |
|---|---|
| ![Old Tasks app](https://user-images.githubusercontent.com/42591237/123796119-12d52100-d8e5-11eb-8110-46ec599ae571.png) | ![Mockup new Tasks app](https://user-images.githubusercontent.com/42591237/123796151-1a94c580-d8e5-11eb-8014-f7059a46dcd9.png) |

So a few points to discuss:
1. The avatars and numbers in the navigation panel are too close to the right side (needs to be fixed in the vue components, afaik)
2. I've moved the settings entry into the main view because of https://github.com/nextcloud/server/issues/25953 (there it is much better to find); the settings would need to be moved into a settings modal first
3. Aligned the navigation toggle to fit the design better (needs to be addressed in the vue components, afaik)
4. The `Add a task to Persönich` is still an input field but has now rounded corners because it looked like a search field before with nearly square shape; has also an icon now. When clicking into it, the cursor should stay at the right from the plus icon which should stay there; the text `Add task to Persönlich` should then get hidden
5. The stars on the right of the tasks should be the outline ones and not filled which looks better, imo
6. Load all completed tasks has now a minimal clickable size of 44px like other components and an icon, too.
7. The text and icons in the top bar are now black to make them better visible
8. I've made `Load all completed Tasks` better clickable by increasing the size

## Mobile
| Before | After |
|---|---|
| ![Old Tasks app mobile](https://user-images.githubusercontent.com/42591237/123796267-3bf5b180-d8e5-11eb-9639-0df8612051a6.jpeg) | ![Mockup new Tasks app mobile](https://user-images.githubusercontent.com/42591237/123796282-41eb9280-d8e5-11eb-8066-f9702046af7c.jpeg) |

Some additional things to discuss here:
1. the navigation panel was also moved into place here (also needs to be fixed in the vue components)
2. Maybe the `Add a task to Persönlich` Could function here as a real button which would open the sidebar of a new task directly when clicking and focusing on the title? Because creating many new tasks isn't as important on mobile,  I think.

---

cc @nextcloud/designers

**Comment by raimund-schluessler** [comment] 2021-06-29 13:10
@szaimen Thanks for the input. Unfortunately, you compare Tasks v0.13.6, but since then, quite some stuff has changed which will come with v0.14.0.

The app looks like this at the moment:
<img width="1279" alt="Tasks" src="https://user-images.githubusercontent.com/2496460/123801729-d6a4bf00-d8ea-11eb-8d61-696fcb80e680.png">

Regarding your points:
>    1. The avatars and numbers in the navigation panel are too close to the right side (needs to be fixed in the vue components, afaik)

This has been fixed already.

>    2. I've moved the settings entry into the main view because of [UX: Placement of application settings shows poor performance with naive users server#25953](https://github.com/nextcloud/server/issues/25953) (there it is much better to find); the settings would need to be moved into a settings modal first

To be honest, I don't really like it there. The bottom sidebar region is fine in my opinion. And how often do you need this settings button honestly? But anyway, that's a global Nextcloud decision that needs to be changed in the vue-components. So nothing to fix here in the Tasks repo.

>    3. Aligned the navigation toggle to fit the design better (needs to be addressed in the vue components, afaik)

This will be changed in the vue-components to be aligned correctly (might need adjustments here).

>    4. The `Add a task to Persönich` is still an input field but has now rounded corners because it looked like a search field before with nearly square shape; has also an icon now. When clicking into it, the cursor should stay at the right from the plus icon which should stay there; the text `Add task to Persönlich` should then get hidden

For me, this looks to much like a button now (compare the other buttons), and not like an input anymore.

>    5. The stars on the right of the tasks should be the outline ones and not filled which looks better, imo

I guess this is personal preference. We use filled stars throughout Nextcloud (see the Favorite star in the files app), and we won't change it only here.

>    6. Load all completed tasks has now a minimal clickable size of 44px like other components and an icon, too.

Fine with me. My intention was to not make this button to prominent, since it is rarely used. But making it 44 px clickable area is good, I guess.

>    7. The text and icons in the top bar are now black to make them better visible

Personal preference, which I don't really like.

>    8. I've made `Load all completed Tasks` better clickable by increasing the size

Duplicate of number 6, I think?

@szaimen Could you please create separate issues for points 3 and 6, please? The rest needs to be decided in other repositories or is a personal preference, I think.

**Comment by szaimen** [comment] 2021-06-29 13:57
I'll open new ones for 3 and  6 in a second. Just one last idea: What do you think of printing the letters in the input box in bolt and adding a plus in front of it? (I usually find icons more clear than text)

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/123810271-8e899a80-d8f2-11eb-8598-716d8e445b87.png) | ![image](https://user-images.githubusercontent.com/42591237/123810298-934e4e80-d8f2-11eb-83c8-c98bad17ae2b.png) |

**Comment by szaimen** [comment] 2021-06-29 15:17
Two other ideas that were part of the mockup come to my mind now that I think about it that weren't discussed yet:
1. What about substituting the settings icon through a material design one?
2. What do you think about my idea of making the `Add task list` a "real" button by adding an outline?

**Comment by raimund-schluessler** [comment] 2021-06-29 15:21
>    1. What about substituting the settings icon through a material design one?

I am all for it. But that needs to be done in the vue-components.

**Comment by nimisha-vijay** [comment] 2021-06-30 12:40
Many of these do make sense but are not consistent with Nextcloud design generally.


> I've moved the settings entry into the main view...

The settings is usually a global settings dialogue which doesn't change, moving it into the main view would make it seem like it is associated with the content which usually changes. 


> The ```Add a task to Persönich``` is still an input field but has now rounded corners because it looked like a search field before with nearly square shape; has also an icon now.

> What do you think of printing the letters in the input box in bolt and adding a plus in front of it?

You're right, the "Add task" action could be a bit more present and I like the idea of adding a + at the beginning. Generally we don't use bold text in inputs.


>  Because creating many new tasks isn't as important on mobile, I think.

It's a better idea to try to maintain consistency in functionality between desktop and mobile, I'd think. 


> What do you think about my idea of making the Add task list a "real" button by adding an outline?

That sounds like good idea because we can have a primary action in the navigation, but usually when we use buttons, it triggers a change external to it, not within the button. So making it appear like a button but act as a text input may not be a bit confusing. A similar style is also used in Deck for creating a board.

**Comment by szaimen** [comment] 2021-06-30 19:04
@raimund-schluessler so basically adding a `+` before the text in the input field should be worth a try.

**Comment by raimund-schluessler** [comment] 2021-07-13 07:26
I think we now have separate issues for all improvements proposed. So I am closing this one here.

**Closed by raimund-schluessler** 2021-07-13 07:26 UTC
Labels: design, enhancement
