### ISSUE TITLE
Table layout of settings flyout is broken

### ISSUE THREAD

**Issue by TilmanK** [nextcloud/tasks#210] opened 2018-10-21 14:38 UTC
![settings_menu](https://user-images.githubusercontent.com/8856390/47268331-c6d85880-d54f-11e8-9c25-1c477e742463.PNG)
### Steps to reproduce
Installed fresh Tasks app on Nextcloud 1.14.3. Accessed Tasks for the first time and opened Settings.

### Expected behaviour
Layout of task flyout is aligned

### Actual behaviour
Layout is broken (dropdown menus are shifted downwards.

### Server configuration
**Operating system**: Ubuntu Server 18.04 LTS

**Web server:** Apache2

**Database:** mariadb

**PHP version:** PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )

**Nextcloud version:** Nextcloud 14.0.3

**Tasks version:** 0.9.7

**Updated from an older Nextcloud or fresh install:** Updated from 14.0.2

**Signing status:** No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - audioplayer: 2.4.1
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dashboard: 5.0.1
  - dav: 1.6.0
  - deck: 0.4.1
  - dropit: 0.1.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - music: 0.9.2
  - news: 13.0.2
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - radio: 0.6.3
  - richdocuments: 3.0.1
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

### Client configuration
**Browser:** Chrome Version 69.0.3497.100 (Offizieller Build) (64-Bit)

**Operating system:** Windows 10 64bit

**Comment by raimund-schluessler** [comment] 2018-10-21 19:06
Thanks for the report. This is a duplicate of https://github.com/nextcloud/tasks/issues/77, which was fixed with https://github.com/nextcloud/tasks/commit/9ee6d23acad71251811a6b4e0e6656849829935d. Will be available with the next release. As a workaround: It works on Firefox.

**Closed by raimund-schluessler** 2018-10-21 19:06 UTC
