### ISSUE TITLE
Drop-down calendar hiden behind the other components

### ISSUE THREAD

**Issue by cieska** [nextcloud/tasks#1181] opened 2020-08-08 12:50 UTC
First of all, I want to thank you for making Tasks more user friendly and more useful. It's really getting the shape as a mature product. I do like the better display of the tasks and framing, that each list item stands out and not blends too much in the background. Well done. 
Sure this topic, not about that, but a few things can be improved. For example, the task comment section is ridiculously narrow and very annoying when there are more than a few words. Would be nice if it can be as wide as possible, maybe removing the extra table frame could help, or reducing margins, but in the same time that would be nicely separated from other properties listed. I think would be ideal if the right properties field to be slide adjustable to your needs, as sometimes seems a middle portion of the task list is too wide to display just name of the task which usually just a few words. But I guess this is not the App issue but Nextcloud structure. Screenshot attached.
![Screenshot_20200808_133939](https://user-images.githubusercontent.com/41318524/89710805-f43d0300-d97d-11ea-8ed8-64a33d1c3ef7.png)

### Steps to reproduce
1. On smaller display 
2. Set Start day / Set Do Day drop-down calendar of the task properties table on the right.

### Expected behaviour
Drop-down calendar table should be visible fully and not to be hidden behind the middle table of the main task list.

### Actual behaviour
It depends how wide the browser is open on the actual display and resolution ratio the drop-down calendar table is more or less hidden and not can be used as supposed to. Screen-shot attached.
![Screenshot_20200808_131104](https://user-images.githubusercontent.com/41318524/89710495-81cb2380-d97b-11ea-80cd-8e95fef82e87.png)

### Server configuration
Server configuration detail

Operating system: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64

Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)

Database: mysql 5.7.31

PHP version: 7.2.24-0ubuntu0.18.04.6

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

Nextcloud version: 18.0.7 - 18.0.7.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - breezedark: 18.0.21
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.7
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - cookbook: 0.7.6
 - dav: 1.14.0
 - deck: 1.0.5
 - event_update_notification: 1.0.2
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_fulltextsearch: 1.4.3
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.2
 - groupfolders: 6.0.6
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - news: 14.1.11
 - nextcloud_announcements: 1.7.0
 - notes: 3.6.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.3
 - telephoneprovider: 1.0.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - bookmarks
 - encryption
 - federation
 - files_external
 - fulltextsearch_elasticsearch
 - ocr
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.arentop.com",
        "nx.are.lab"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.xxx.com",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "18.0.7.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "updater.release.channel": "stable",
    "theme": "",
    "loglevel": 2,
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "app_install_overwrite": [
        "calendar"
    ]
}

</details>

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
```

**Are you using external storage:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox, opera

**Operating system:** kubuntu

**Comment by raimund-schluessler** [comment] 2020-08-08 14:44
Thanks for the feedback. We currently rework the sidebar, see https://github.com/nextcloud/tasks/issues/664 and #1030 and we can take care of reducing the margin of the comments field there. Resizing the sidebar would need to be implemented by the nextcloud-vue components.

The datepicker issue is a duplicate of https://github.com/nextcloud/tasks/issues/935 and will be solved with #1030 as well.

Since both issues are tracked already, I will close this issue here.

**Closed by raimund-schluessler** 2020-08-08 14:44 UTC
