### ISSUE TITLE
sub-tasks due today don't show up in "today" view

### ISSUE THREAD

**Issue by zeroepix** [nextcloud/tasks#824] opened 2020-01-24 07:12 UTC
### Steps to reproduce
1. Create a task, add a subtask
2. Set a due date for whatever your date is today for the subtask, leave the parent task without one
3. Click "Today" filter and look for your new task or subtask

### Expected behaviour
That the subtask appears in the Today view. Either by:-
1. Itself, 
2. Itself and its un-dated parent, or
3. The entire parent branch as if that was due today (less preferred option)

### Actual behaviour
No idea that the subtask is due today, it gets missed until you look at the project view and panic.

**Comment by raimund-schluessler** [comment] 2020-01-24 08:10
Duplicate of #83, was fixed with #431 and will be released with v0.12.0.

**Closed by raimund-schluessler** 2020-01-24 08:10 UTC
