### ISSUE TITLE
(Feature request) Show upcoming tasks in Dashboard 'Upcoming Events' pane.

### ISSUE THREAD

**Issue by Ruthalas** [nextcloud/tasks#1396] opened 2021-01-19 04:31 UTC
It would be really cool if upcoming tasks were visible in the Dashboard 'Upcoming Events' pane, the same way upcoming Deck cards are.

I know there's another issue for making a dedicated Tasks widget for the Dashboard (issue 1243), but this seems like a different functionality, and possibly a simple one(?).

Thanks for the app!

**Comment by Mela** [comment] 2021-06-12 13:53
Yes, please. A own "tasks" pane also would be very welcome.

**Comment by jakobroehrl** [comment] 2021-06-14 07:51
duplicate of https://github.com/nextcloud/tasks/issues/1243

**Comment by raimund-schluessler** [comment] 2021-06-14 07:55
Let's track this is #1243. If you want the Calendar app widget to show tasks as well, please report this in the Calendar repository (although I think having a dedicated Tasks widget is the better solution).

**Closed by raimund-schluessler** 2021-06-14 07:55 UTC
