### ISSUE TITLE
503 error after fresh install

### ISSUE THREAD

**Issue by MargotSz** [nextcloud/tasks#1258] opened 2020-10-07 02:30 UTC
### Steps to reproduce
1. Fresh Instal NextCloud 20 via FTP
2. Enable server side encryption
3. Installing apps:
3.1 Deck
3.2 Task
4. Opening Task tab

### Expected behaviour
Task site will show up

### Actual behaviour
Site with "503 Service Unavailable The server is temporarily busy, try again later!"

### Server configuration

Operating system: Linux 3.10.0-962.3.2.lve1.5.36.el7.x86_64 #1 SMP Mon May 18 02:16:06 EDT 2020 x86_64

Webserver: LiteSpeed (litespeed)

Database: mysql 10.2.26

PHP version: 7.4.10

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, i360, bcmath, dom, fileinfo, gd, imagick, imap, intl, json, exif, mysqli, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, soap, sockets, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 20.0.0 - 20.0.0.9

**Tasks version:** - tasks: 0.13.3

**Updated from an older Nextcloud or fresh install:** Fresh

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - deck: 1.1.0
 - encryption: 2.8.1
 - end_to_end_encryption: 1.6.2
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.5.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.4
 - richdocumentscode: 4.2.800
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.3
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
```

**Nextcloud configuration:**

```
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "chmu.ro"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.0.9",
    "overwrite.cli.url": "https:\/\/chmu.ro",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true
}

```
External storages: files_external is disabled

Encryption: yes

User-backends: OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 (same errot with chrome)

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"BvI7zzz5EH9YDCfYIJI5","level":3,"time":"2020-10-07T02:27:03+00:00","remoteAddr":"37.120.211.206","user":"Margot","app":"PHP","method":"GET","url":"/ocs/v2.php/search/providers/talk-message/search?term=task&from=%2Fsettings%2Fapps","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"20.0.0.9"}
{"reqId":"aaCKwRQUO67bvjWD2Cd1","level":3,"time":"2020-10-07T02:27:25+00:00","remoteAddr":"37.120.211.206","user":"Margot","app":"PHP","method":"GET","url":"/index.php/settings/apps/installed/tasks","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"20.0.0.9"}
{"reqId":"vNplM6kQDg63G6Pe8COA","level":3,"time":"2020-10-07T02:27:26+00:00","remoteAddr":"37.120.211.206","user":"Margot","app":"PHP","method":"PUT","url":"/index.php/apps/user_status/heartbeat","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"20.0.0.9"}
{"reqId":"JkM1c4zqkAM7gZ5usZW8","level":3,"time":"2020-10-07T02:27:26+00:00","remoteAddr":"37.120.211.206","user":"Margot","app":"PHP","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fsettings%2Fapps%2Finstalled%2Ftasks","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"20.0.0.9"}
{"reqId":"hyM4rx4JbVeGgx3qtFAM","level":3,"time":"2020-10-07T02:27:26+00:00","remoteAddr":"37.120.211.206","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"Directive 'allow_url_include' is deprecated at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"20.0.0.9"}
```

**Comment by MargotSz** [comment] 2020-10-07 02:47
Interestingly:
  The calendar with tasks works fine. Same as syncing tasks with DAVx5 and the Task app on your phone.

**Comment by raimund-schluessler** [comment] 2020-10-07 05:36
Sounds like a duplicate of #1251.

**Closed** 2020-10-10 10:36 UTC
