### ISSUE TITLE
Tasks app has no tab/page icon

### ISSUE THREAD

**Issue by ygoe** [nextcloud/tasks#149] opened 2018-02-21 10:14 UTC
### Steps to reproduce
1. Open the app page

### Expected behaviour
There should be an icon in the browser tab header like for all other apps and most other websites.

### Actual behaviour
No icon, just the page title.

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** pgsql PostgreSQL 10.2 (Ubuntu 10.2-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.25-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** downloaded PHP files and followed instructions

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - comments: 1.3.0
 - contacts: 2.1.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.0
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - gallery
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mydomain.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.mydomain.de\/",
    "htaccess.RewriteBase": "\/",
    "dbtype": "pgsql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** Windows 10

**Comment by raimund-schluessler** [comment] 2018-02-21 10:20
There is an icon for the app and it is working for all my (test) instances. So something must be wrong with your configuration. Please provide the server configuration and how you installed the app (manually or by the app store).

**Comment by ygoe** [comment] 2018-02-21 12:04
I have added the information. There is no and has never been an icon for me. Not in Firefox and not in Chrome. The ad blocker reports it has not blocked anything on the page. I have installed the app through the integrated UI.

**Comment by raimund-schluessler** [comment] 2018-02-21 12:35
This is weird. Is it only happening for this app?

**Comment by ygoe** [comment] 2018-02-21 13:24
Nothing in the browser console. But I have this in the HTML: `<link rel="icon" href="/apps/theming/favicon/tasks?v=4">` Looks a bit different. There's no request in the network log, so the browser doesn't seem to have interest in this. Maybe because it doesn't have an extension nor a type attribute. When I manually request that URL I get "this image can't be displayed because it contains errors". Saving it as the suggested name "favIcon-tasks.ico" writes an empty file.

**Comment by raimund-schluessler** [comment] 2018-02-21 13:45
Could you please try to disable the theming app and check if the icon appears?

**Comment by raimund-schluessler** [comment] 2018-02-21 13:48
I very much believe that this is actually caused by a server issue: https://github.com/nextcloud/server/issues/7945

**Comment by ygoe** [comment] 2018-02-21 18:33
Disabling the Theming app instantly makes the Tasks app icon visible.

**Comment by raimund-schluessler** [comment] 2018-02-21 22:06
I just checked with Theming app enabled and the Tasks icon is shown correctly for me. However, a different app failes to show the favicon.

I will close this, since it is very likely not related to the Tasks app itself, but rather caused by the theming app and https://github.com/nextcloud/server/issues/7945.

**Closed by raimund-schluessler** 2018-02-21 22:06 UTC

**Comment by drpetersen** [comment] 2019-05-13 08:45
Sorry for necroposting, but I used to have the same problem on my nc 16 (and a number of previous versions as well), and just discovered a fix (or workaround):
Disabling the Theming app does not help. What did, though, was 

* uploading a custom favicon (after re-enabling the Theming app, of course)
* and then deleting that custom favicon again.

This restored the Tasks app icon for me. Hope this is helpful to someone.
