### ISSUE TITLE
NextCloud 13

### ISSUE THREAD

**Issue by Larsene** [nextcloud/tasks#136] opened 2017-12-17 17:21 UTC
Please, make it compatible with NextCloud 13, this app is so useful !

**Comment by raimund-schluessler** [comment] 2017-12-17 18:38
It is already, just not released to the appstore yet.

**Comment by yan12125** [comment] 2017-12-18 11:22
I can confirm git-master works with Nextcloud 13 beta 3. Hope a new release will be tagged soon 👍

**Comment by raimund-schluessler** [comment] 2017-12-18 21:04
@skjnldsv What would be the best way to proceed here? Release a version 0.9.6 compatible with NC12 and 0.9.7 compatible with NC13? I guess there is not really a way to have one version compatible with both NC12 and 13?

**Comment by skjnldsv** [comment] 2017-12-19 06:47
You can make a single release compatible if you want :)
You need to add a css fallback for 12 with the props you need from server's apps.scss.

Then ship it. ;)
You will then remove the fallback when your min-version will be at least 13 :)

**Comment by raimund-schluessler** [comment] 2017-12-19 08:39
> You can make a single release compatible if you want :)

This sounds good. Are there examples how to do this?

**Comment by skjnldsv** [comment] 2017-12-19 16:38
See the mail app! :)
We edited the template to fit the css guidelines and create a nc13 compatibility, then we copied the needed rules from apps.scss to the mail scss (but only the needed one!)

https://github.com/nextcloud/mail/pull/565
https://github.com/nextcloud/mail/pull/594

**Comment by acidwars** [comment] 2017-12-20 10:48
@yan12125 I can't confirm this! I also cloned the master to my apps folder which resulted in not working CSS.

**Comment by yan12125** [comment] 2017-12-20 11:54
@acidwars: I didn't clone the repo to the apps folder. My steps are a little bit complicated and those are useful for Arch Linux-based systems only (Manjaro, Antergos, ...). Here are details:
1. Clone https://aur.archlinux.org/nextcloud-app-tasks-git.git
2. Replace ```yarn``` with ```npm``` in PKGBUILD
3. Run ```makepkg```
4. Install the package via ```sudo pacman -U```. Now the old nextcloud-app-tasks will be uninstalled
5. Run nextcloud again

I guess there are some build steps to generate CSS files, so simply cloning the repo won't work.

**Comment by acidwars** [comment] 2017-12-20 11:57
Thanks I will try that!!

**Comment by raimund-schluessler** [comment] 2017-12-20 12:10
The repository is not meant for production use. Various JS libraries are not present here, which have to be pulled from their own repositories. Also, the CSS code for the icon sprite files needs to be compiled.

If you really want to use the app from the repository source code, you need to run the [make](https://github.com/nextcloud/tasks/blob/master/Makefile) file.

**Comment by Larsene** [comment] 2017-12-21 10:24
Thanks for all your answers. As i'm using NextCloud 13 B 3 in production (i know, beta != production), i'll wait to reinstall this app from the store.

Definitively, thanks for this useful app ! Can't wait to work with again :-)

**Comment by nougad** [comment] 2017-12-25 18:21
Any plans when the version is available in the NC store?

**Comment by valir** [comment] 2017-12-29 00:10
Thanks for this great app. I'd have a suggestion about NC13. 

Just updated to NC 13 Beta 3 and I this app and the two factor authentication app where incompatible. However the TOTP App already had a new version available so I just clicked the update button after returning to the NC instance, after the upgrade. Maybe do the same here?

**Comment by raimund-schluessler** [comment] 2017-12-29 08:24
There will be a version for NC13 on the appstore. The app is already compatible with NC13, but atm this breaks compatibility with NC12. Since I want to support both versions, we have to do some more work. It will be released once this is done.

**Comment by MichaIng** [comment] 2018-01-06 00:50
Hmm, I just adjusted info.xml to allow enabling v0.9.5 on NC13 Beta and it works without recognized issues.

What exactly breaks usage on NC12+NC13?

**Comment by frogueat** [comment] 2018-01-12 15:10
omg - in my instance, the ui is completly broken :-o Got the app through git by sudo git clone https://github.com/nextcloud/tasks.git . That app is so great and i use it on a dayly basis. pls pls ....
![bildschirmfoto 2018-01-12 um 16 08 04](https://user-images.githubusercontent.com/1876291/34881119-e8ef9f3a-f7b2-11e7-818e-305689eba580.png)

**Comment by raimund-schluessler** [comment] 2018-01-12 15:14
@frogueat Getting it by git is not meant for production. If you do it like this, you need to run the makefile as well, otherwise, all javascript and css is missing. This leads the issue you have in the screenshot.

There will be a version in the appstore, I just need to find the time to prepare everything.

**Comment by frogueat** [comment] 2018-01-12 15:30
Did sudo make. Looked good, many npm-activities ;-) but in the end, the app's ui didnt change much ;-) Seems like i have to wait for the app-store. Looking forward to :-)

**Comment by mikweb2017** [comment] 2018-01-25 15:33
Please, make it compatible with NextCloud 13, this app is so useful !

**Comment by Mortal** [comment] 2018-01-27 22:11
If you have Docker but don't have npm installed, then you can use my pull request to build your own Tasks for Nextcloud 13: https://github.com/nextcloud/tasks/pull/141

**Comment by xf-** [comment] 2018-01-30 16:00
v13 stable will be released tomorrow

**Comment by raimund-schluessler** [comment] 2018-01-30 17:29
I know guys, sorry that no compatible version is in the appstore yet. I was very busy with other stuff and will likely not have time before the weekend either. But there will be a release, just stay patient a bit, please.

**Comment by yan12125** [comment] 2018-01-31 15:14
Looks like the 13.0 release is delayed - https://github.com/nextcloud/server/pull/8109#issuecomment-361957109

**Comment by xf-** [comment] 2018-02-06 10:09
And now released

**Comment by raimund-schluessler** [comment] 2018-02-06 10:20
I am working on it, I hope to finish it in the next days. If not, I will upload a signed version for NC13 to github, for manual install at least.

**Comment by skjnldsv** [comment] 2018-02-06 14:59
@raimund-schluessler is there anything I can do to  help?

**Comment by m3m0n** [comment] 2018-02-06 16:11
Thank you for your hard work and sacrificing your time for this. It is much appreciated.

**Comment by raimund-schluessler** [comment] 2018-02-06 16:27
@skjnldsv I would like to have one version for NC12 and NC13. I started to fix everything which is not working in NC12 anymore by copying the missing rules from NC13 server to the app. I haven't pushed what I have done so far, but I will create a (yet incomplete) PR today. If you have time to help on that, it would be great. Also testing the fixes on a NC12 instance would already help.

**Comment by raimund-schluessler** [comment] 2018-02-06 20:16
PR in https://github.com/nextcloud/tasks/pull/142

**Comment by raimund-schluessler** [comment] 2018-02-07 20:54
The version for NC13 is in the appstore now (works with NC12 as well). Have fun!

**Closed by raimund-schluessler** 2018-02-07 20:54 UTC

**Comment by skjnldsv** [comment] 2018-02-07 22:00
You're awesome @raimund-schluessler ! :)

**Comment by frogueat** [comment] 2018-02-08 05:54
Looks great! And manual sorting do make sense a lot! Thx!

**Comment by Ricardosgeral** [comment] 2018-02-09 11:10
yes it's working ok thansks
