### ISSUE TITLE
Bug when drag and dropping a task to other lists, but passing through other tasks on the way

### ISSUE THREAD

**Issue by Klemet** [nextcloud/tasks#1799] opened 2021-09-28 02:38 UTC
### Steps to reproduce
1. Create a task in list 1 (which already contains other tasks)
2. Drag the task by left-clicking on it; drop it into list 2, but move it near the other tasks of list 1 on the way (near enough to activate changes in the disposition of the other tasks of list 1, as a preview of where the selected tasks can land)
3. Go into list 2, and try to drag and drop the task that you just transferred into list 2 back into list 1. The mention "An error occurred" will happen, preventing from putting the task back to list 1.

### Expected behaviour
The task should go back into list 1 without any issues.

### Actual behaviour
The mention "An error occurred" will appear. The only way to put the task back to its previous list is by deleting it and recreating it entirely. I suspect that when doing a drag and drop in this way, a copy of the task is kept in list 1, preventing it from being put back into it.

## Server configuration detail

**Operating system:** Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.3.31

**PHP version:** 

7.4.23
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 22.1.1 - 22.1.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - apporder: 0.13.0
 - breezedark: 22.0.1
 - calendar: 2.3.3
 - carnet: 0.24.2
 - circles: 22.1.1
 - cloud_federation_api: 1.4.0
 - cms_pico: 1.0.16
 - comments: 1.11.0
 - contacts: 4.0.3
 - contactsinteraction: 1.2.0
 - cospend: 1.3.19
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.3
 - drawio: 1.0.1
 - external: 3.9.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - gpxedit: 0.0.14
 - guests: 2.0.2
 - issuetemplate: 0.7.0
 - joplin: 0.0.25
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.4
 - maps: 0.1.9
 - nextcloud_announcements: 1.11.0
 - notes: 4.1.1
 - notifications: 2.10.1
 - notify_push: 0.2.4
 - oauth2: 1.9.0
 - password_policy: 1.12.0
 - phonetrack: 0.6.9
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - tasks: 0.14.2
 - text: 3.3.0
 - theming: 1.12.0
 - theming_customcss: 1.9.0
 - twofactor_backupcodes: 1.10.1
 - unsplash: 1.2.3
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - weather_status: 1.1.0
 - webapppassword: 21.7.0
 - workflowengine: 2.3.1
Disabled:
 - admin_audit
 - cookbook
 - encryption
 - files_texteditor
 - gpxpod
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "skeletondirectory": "\/var\/www\/html\/themes\/hetzner\/skeleton",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nx12716.your-storageshare.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.1.1.2",
    "overwrite.cli.url": "https:\/\/nx12716.your-storageshare.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "log_type": "syslog",
    "syslog_tag": "nextcloud-nx12716",
    "simpleSignUpLink.shown": false,
    "upgrade.disable-web": true,
    "updatechecker": false,
    "theme": "hetzner",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "app_install_overwrite": [
        "joplin",
        "issuetemplate"
    ],
    "has_rebuilt_cache": true,
    "loglevel": 2,
    "maintenance": false,
    "appstoreurl": "https:\/\/apps.your-storageshare.de"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Operating system:** Windows 10

**Comment by raimund-schluessler** [comment] 2021-09-28 05:41
Duplicate of #1685.

The reason why this happens is the new CalDAV trash bin feature of NC server. Tasks don't get deleted anymore, but just marked as deleted, also when moved. Hence, the task is still in list1 (just marked as deleted) and moving it back will fail. Requires fixes in NC server.

**Closed** 2021-09-28 05:42 UTC

**Comment by Klemet** [comment] 2021-09-28 13:12
Thank you so much, @raimund-schluessler ! That makes a lot of sense, and I'm glad that there is a small workaround for this. I still hope that this could be fixed on the server side.

I'm sorry that I didn't find #1685 ; I did search, but didn't use the right keywords, it seem.

Have a nice day !

**Comment by raimund-schluessler** [comment] 2021-09-28 13:18
> I'm sorry that I didn't find #1685 ; I did search, but didn't use the right keywords, it seem.

No problem!

There will be a proper fix for it at some point.
