### ISSUE TITLE
[feature request] Sharing a task list with a public web link

### ISSUE THREAD

**Issue by kosssi** [nextcloud/tasks#1471] opened 2021-04-02 16:38 UTC
### Expected behaviour
I would like share a task list like I share a calendar with a public link.

### Actual behaviour
I can share a task list only with Nextcloud user.

### Server configuration
Nextcloud 21
Task 0.13.6

**Comment by raimund-schluessler** [comment] 2021-04-04 19:43
Duplicate of #469.

**Closed by raimund-schluessler** 2021-04-04 19:43 UTC
