### ISSUE TITLE
make percentage fully visible

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/tasks#2582] opened 2024-05-21 18:35 UTC
### Steps to reproduce

1. make use of the Tasks App
2. establish a new task
3. change the percentage by any means

### Expected behavior

Digits are fully visible i.e. readable in a two to three digit wide box as applicable.

### Actual behaviour

![Bildschirmfoto 2024-05-21 um 17 36 25](https://github.com/nextcloud/tasks/assets/4863737/7d0fba54-3353-463a-b30b-05c42423a189)

Digits are unreadable in a too narrow box.

### Tasks app version

0.15.0

### Browser

Firefox ESR 115.11.0 / Safari 17.5

### Client operating system

macOS 13

### Server operating system

GNU/Linux Debian 12.5 Bookworm

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.9

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

German (DE) locale

**Comment by raimund-schluessler** [comment] 2024-05-21 18:37
Duplicate of #2304.

**Closed** 2024-05-21 18:37 UTC
Labels: bug, 0 - to triage
