### ISSUE TITLE
Task list name cannot be modified

### ISSUE THREAD

**Issue by nursoda** [nextcloud/tasks#777] opened 2019-12-22 13:08 UTC
### Steps to reproduce
1. create a TASK ONLY task list
2. share it, it's shared as "list name (owner name)"
3. as the one the list was shared-to, rename it:
4. the correctly filled-out rename dialog text field is there but one cannot modify its text. Changing color works fine.

### Expected behaviour
One should be able to rename task-only lists that were shared by someone, like one can rename calendars.

### Actual behaviour
One cannot perform the actual rename.

### Server configuration
// sidenote: https://apps.nextcloud.com/apps/issuetemplate is not available for NC 17+18.
**Operating system:** Arch Linux (current except for PHP since NC isn't compatible with PHP 7.4)
**Web server:** NGINX
**Database:** MariaDB
**PHP version:** 7.3(!)
**Nextcloud version:** 17.0.2
**Tasks version:** 0.11.3
**Updated from an older Nextcloud or fresh install:** Updated from 13…14…15…16
**Signing status:** Clean
**List of activated apps:**: 
// sidenote: bug report template requests to report all installed apps. That is, in quite some cases, too much information to reveal to public. Here's the part that *might* be relevant. Enabled apps:
  - calendar: 1.7.1
  - tasks: 0.11.3
  - …
**Nextcloud configuration:**
// sidenote: bug report template requests to report config:list. That is definitely too much information to reveal to public. What is it actually that you typically need from the config?
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 71
**Operating system:** Arch Linux (current)
**CalDAV-clients:** multiple, but regarding the bug only the web app itself is relevant

### Logs
Logs are not relevant, but JS console is:
1. The escapeHTML library is deprecated! It will be removed in nextcloud 19. 72 globals.js:26:15
2. TypeError: "document.querySelector(...) is null"
    edit tasks.js:2
    VueJS 2
        ee
        Xt
vue.runtime.esm.js:1888:12

**Comment by raimund-schluessler** [comment] 2019-12-23 11:46
I can confirm the issue, not sure why this is the case, though.

Also, although unrelated, one cannot click into the displayname field, but has to use the cursor keys to place the cursor.

**Comment by raimund-schluessler** [comment] 2019-12-23 11:48
@georgehrke Is it the expected behaviour that you cannot change the calendar name of a calendar shared with you?

**Comment by raimund-schluessler** [comment] 2019-12-23 12:02
Ok, now I got it. This is actually how it is supposed to be.

You edit (rename, change color) YOUR version of the calendar / task list. This works the same in the calendar app. This is done, so everyone can choose his own color for the calendar and also rename it as one wants. So edits are saved, but you cannot mess with how others name or colored the same calendar.

Closing, since this is the expected behaviour.

Issue for not beeing able to click into the displayname field is https://github.com/nextcloud/tasks/issues/779.

**Closed by raimund-schluessler** 2019-12-23 12:02 UTC
Labels: bug

**Comment by nursoda** [comment] 2019-12-24 18:42
> Ok, now I got it. This is actually how it is supposed to be.

Well, yes, apart from not being able to modify the name, which is what this bug is about. But I confirm that adding ", preventOnFilter: false" (see #779) fixes the issue.

**Comment by raimund-schluessler** [comment] 2019-12-24 20:57
Since the input field is auto-focused when you open the sharing menu, you should be able to type and set the cursor position with the arrow keys also without the fix in #780. Anyway, good to hear that #780 fixes your issue and merry christmas as well 🙂
