### ISSUE TITLE
Moving Tasks results in broken tasks

### ISSUE THREAD

**Issue by thomasfrobieter** [nextcloud/tasks#1929] opened 2022-02-22 12:29 UTC
Current stable release: moving a task into another category brakes the task. Unable to move it back, console:

> [XHR] MOVE https://foobar.com/remote.php/dav/calendars/USERX/1667919084279873511/4610247574769071552.ics
> [HTTP/1.1 400 Bad Request 643ms]

![grafik](https://user-images.githubusercontent.com/4060313/155130789-0d42c7be-d479-4de4-b884-c2e0368f93cb.png)

> Error: 
>     y dist.js:1
>     _ dist.js:1
>     E dist.js:1
>     onreadystatechange dist.js:1
>     exports dist.js:1
>     request dist.js:1
>     move dist.js:1
>     move dist.js:1
>     n tasks.js:1339
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     promise callback*Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     moveTask tasks.js:1360
>     v vuex.esm.js:631
>     dispatch vuex.esm.js:831
>     dispatch vuex.esm.js:172
>     e tasks.js:1329
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     n tasks.js:1338
>     n tasks.js:1329
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     moveTask tasks.js:1360
>     v vuex.esm.js:631
>     dispatch vuex.esm.js:831
>     dispatch vuex.esm.js:172
>     r vuex.esm.js:551
>     dropTask ListItemCalendar.vue:259
>     drop ListItemCalendar.vue:466
>     VueJS 3
> [tasks.js:1354:11](webpack:///tasks/src/store/tasks.js)
>     n tasks.js:1354
>     (Async: promise callback)
>     n tasks.js:1353
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     (Async: promise callback)
>     Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     moveTask tasks.js:1360
>     v vuex.esm.js:631
>     dispatch vuex.esm.js:831
>     dispatch vuex.esm.js:172
>     e tasks.js:1329
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     n tasks.js:1338
>     n tasks.js:1329
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Wp calendars.js:938
>     o calendars.js:941
>     qp calendars.js:952
>     qp calendars.js:941
>     moveTask tasks.js:1360
>     v vuex.esm.js:631
>     dispatch vuex.esm.js:831
>     dispatch vuex.esm.js:172
>     r vuex.esm.js:551
>     dropTask ListItemCalendar.vue:259
>     drop ListItemCalendar.vue:466
>     VueJS 3

Furthermore some of the subtasks still show up in the original category as first level tasks. After the page is reloaded, the tasks are moved back to the new category as subtasks (like they should). Switching back to the original categetory again, the subtasks appearing on the first level.

Now i cant move them in any way, because of the JS errors shown above.

Cleared browsercache, re-logged, nothing helps.

**Comment by raimund-schluessler** [comment] 2022-02-22 13:55
Duplicate of https://github.com/nextcloud/tasks/issues/1685.

This is a problem of Nextcloud server. Moving tasks puts them in the trash bin, and the tasks in the trash bin prevent moving the task back from the second calendar. Just clear the trash bin content (or only the tasks in question) and moving back will work.

**Closed by raimund-schluessler** 2022-02-22 13:55 UTC

**Comment by thomasfrobieter** [comment] 2022-02-22 15:03
@raimund-schluessler Thanks you so much, sadly opening the trash bin also throws a JS error:

> **TypeError: t.calendar is undefined**

> e uidToColor.js:98
>     items uidToColor.js:71
>     VueJS 3
>     fn Trashbin.vue:214
>     VueJS 2
>     T AppNavigationItem.js:66
>     VueJS 14
>     e Trashbin.vue:117
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Ts AppNavigationSettings.vue:1
>     o AppNavigationSettings.vue:1
>     promise callback*Ts AppNavigationSettings.vue:1
>     o AppNavigationSettings.vue:1
>     ys AppNavigationSettings.vue:1
>     ys AppNavigationSettings.vue:1
>     onShow Trashbin.vue:121
>     click Trashbin.vue:209
>     VueJS 4
>     onClick AppNavigationItem.js:66
>     VueJS 3
> [vue.runtime.esm.js:1422:6](webpack:///tasks/node_modules/vue/dist/vue.runtime.esm.js)
>     VueJS 17
>     e Trashbin.vue:117
>     u runtime.js:63
>     _invoke runtime.js:294
>     v runtime.js:119
>     Ts AppNavigationSettings.vue:1
>     o AppNavigationSettings.vue:1
>     (Async: promise callback)
>     Ts AppNavigationSettings.vue:1
>     o AppNavigationSettings.vue:1
>     ys AppNavigationSettings.vue:1
>     ys AppNavigationSettings.vue:1
>     onShow Trashbin.vue:121
>     click Trashbin.vue:209
>     VueJS 4
>     onClick AppNavigationItem.js:66
>     VueJS 3

Is there any OCC command i can use to clear the trash bin? It doesn't seems so: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#dav-commands

**Comment by raimund-schluessler** [comment] 2022-02-22 15:07
Hm, that's probably https://github.com/nextcloud/tasks/pull/1873. You could try to reload the app or try using the Calendar trash bin.

See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#trashbin for the `occ` commands.

**Comment by raimund-schluessler** [comment] 2022-02-22 15:12
I could also no find an occ command for cleaning the trash bin. @ChristophWurst Is there one?

**Comment by thomasfrobieter** [comment] 2022-02-22 15:16
@raimund-schluessler Found a workaround! the trash bin is working on the calendar page itself (/index.php/apps/calendar/dayGridMonth/now) the error just appears on the tasks page. 

While clearing the bin, some weird messages showed up "task cant be restored" for 6/100 tasks, but they where successfully removed also on the second try.

But i still got the JS errors when moving a task into another category :-/ It works for the first move (then i waited a couple of seconds to ensure AJAX stuff has finished), but i cant move it back "An error has occurred".

**Comment by raimund-schluessler** [comment] 2022-02-22 15:23
> But i still got the JS errors when moving a task into another category :-/ It works for the first move (then i waited a couple of seconds to ensure AJAX stuff has finished), but i cant move it back "An error has occurred".

What do you mean with `category`? Calendar? If you move a task from a calendar, the trash bin will be populated. This will happen on every move. So moving back will only work after cleaning the trash bin.
So: Move -> clean -> move back.
This will be fixed in server at some point.

**Comment by thomasfrobieter** [comment] 2022-02-22 17:55
Sorry, yes, I meant calendars. I didn't realize until today that the technical basis for task lists are separate calendars, good to know.

Thx for your help & advice!
