### ISSUE TITLE
[Feature Request] Link files with tasks

### ISSUE THREAD

**Issue by TruputiGalvotas** [nextcloud/tasks#317] opened 2019-03-11 23:50 UTC
### Expected behaviour
It should be possible to link a file with a task

It's actually strange to me that there is no such functionality already since OwnCloud/Nextcloud started as file cloud first..

So there should be a possibility to link a file with a task for convenient access to a file from a task that has related files

**Comment by raimund-schluessler** [comment] 2019-03-12 08:03
Duplicate of #91

**Closed by raimund-schluessler** 2019-03-12 08:03 UTC
