### ISSUE TITLE
copy paste of dummy lists 

### ISSUE THREAD

**Issue by PommensundBier** [nextcloud/tasks#2596] opened 2024-06-11 06:22 UTC
### Is your feature request related to a problem? Please describe.

I often have projects that always require the same steps. I would like to create a basic to-do list that I can copy and adapt. This way I wouldn't have to enter a new list with the same tasks again and again for a new project. A simple duplicate Feature of a List would be very helpful 🙏🏻

**Comment by raimund-schluessler** [comment] 2024-06-25 20:01
I think this is a duplicate of #121. Let me know if you think otherwise.

**Closed by raimund-schluessler** 2024-06-25 20:01 UTC
Labels: enhancement, 0 - to triage

**Comment by WNYmathGuy** [comment] 2024-06-26 19:36
> I think this is a duplicate of #121. Let me know if you think otherwise.

You closed this as a duplicate of an issue that got closed because it claimed this was it's duplicate. 

This, or #121 should be reopened.

Also, I'm not sure why it's so difficult to query all the data of a task list the same way the export to a *.ics does, but instead of exporting it copies it in (imports it) with a new primary key and a dummy name like "Copy Of - silly task list"; maybe even with the default of unchecking all the tasks.

**Comment by raimund-schluessler** [comment] 2024-06-26 19:48
> > I think this is a duplicate of #121. Let me know if you think otherwise.
> 
> 
> 
> You closed this as a duplicate of an issue that got closed because it claimed this was it's duplicate. 
> 
> 
> 
> This, or #121 should be reopened.

#121 is not closed.

> 
> Also, I'm not sure why it's so difficult to query all the data of a task list the same way the export to a *.ics does, but instead of exporting it copies it in (imports it) with a new primary key and a dummy name like "Copy Of - silly task list"; maybe even with the default of unchecking all the tasks.

It sure is not difficult. You are free to implement it, pull requests are always welcome.
