### ISSUE TITLE
Share Feature shows no other users/groups

### ISSUE THREAD

**Issue by cjuenemann** [nextcloud/tasks#1096] opened 2020-06-24 09:49 UTC
#185 # Steps to reproduce
1. Add a new calender with tasks
2. Click on tasks
3. Click on the new task list
4. Click on the share icon

### Expected behaviour
I should be able to add users/groups after i type in their name.

### Actual behaviour
It shows me no results. Even if i only use the first letter.

### Server configuration
**Operating system**
centos 8

**Web server:**
2.4.37 apache

**Database:**
10.3.17-MariaDB Server

**PHP version:**
7.2.24 

**Nextcloud version:**
19.0.0

**Tasks version:**
0.13.1

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:** no idea what i am expect to put here - sorry :(

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

Accessibility 1.5.0
Activity 2.12.0
Antivirus for files 2.4.1		
Calendar 2.0.3
Collaborative tags 1.9.0	
Comments 1.9.0
Contacts Interaction 1.0.0
Custom Properties 1.0.1		
Deleted files 1.9.0	
Federation 1.9.0	
File sharing 1.11.0
First run wizard 2.8.0	
Group folders 6.0.6	
Log Reader 2.4.0	
Monitoring 1.9.0		
Nextcloud announcements 1.8.0	
Notes 3.5.1	
Notifications 2.7.0		
Password policy 1.9.1
PDF viewer 1.8.0	
Photos 1.1.0	
Privacy 1.3.0	
Reader (ebook reader) 1.4.2		
Recommendations 0.7.0	
Right click 0.16.0
Share by mail 1.9.0	
Support 1.2.1	
Tasks 0.13.1
Text 3.0.1
Theming	1.10.0
Two-Factor TOTP Provider 4.1.3
Update notification	1.9.0
Usage survey 1.7.0
Versions 1.12.0
Video player 1.8.0
```

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false
    }
}


**Are you using external storage, if yes which one:** no i do not

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no i do not

### Client configuration
**Browser:** tested my issuse on Chrome 83.0.4103.106 and Firefox 77.0.1

**Operating system:** Windows 10

**CalDAV-clients:** none

### Logs
#### Web server error log
```
tail:
[Tue Jun 23 13:25:05.451742 2020] [core:notice] [pid 742:tid 139634760616256] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jun 24 09:46:13.262954 2020] [mpm_event:notice] [pid 742:tid 139634760616256] AH00492: caught SIGWINCH, shutting down gracefully
[Wed Jun 24 09:46:57.609456 2020] [core:notice] [pid 739:tid 140190112561472] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Jun 24 09:46:57.694671 2020] [suexec:notice] [pid 739:tid 140190112561472] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jun 24 09:46:58.329086 2020] [so:warn] [pid 739:tid 140190112561472] AH01574: module rewrite_module is already loaded, skipping
AH00112: Warning: DocumentRoot [/var/www/html/nextcloud/public.php] does not exist
[Wed Jun 24 09:46:58.335528 2020] [lbmethod_heartbeat:notice] [pid 739:tid 140190112561472] AH02282: No slotmem from mod_heartmonitor
[Wed Jun 24 09:46:58.342581 2020] [mpm_event:notice] [pid 739:tid 140190112561472] AH00489: Apache/2.4.37 (centos) OpenSSL/1.1.1c configured -- resuming normal operations
[Wed Jun 24 09:46:58.342637 2020] [core:notice] [pid 739:tid 140190112561472] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

#### Nextcloud log (data/nextcloud.log)
```
While i search for users/groups the file doesnt expands (checked with tail)
```

#### Browser log
no idea how to find a log with could show the problem - sorry again :(

**Comment by raimund-schluessler** [comment] 2020-06-24 10:47
Could you please check whether sharing a calendar works when using the Calendar app?

**Comment by raimund-schluessler** [comment] 2020-06-26 08:43
@cjuenemann ping.

**Comment by raimund-schluessler** [comment] 2020-06-30 20:43
@cjuenemann Could you please answer the request above?

**Comment by raimund-schluessler** [comment] 2020-07-02 19:37
Closing as there was no feedback and I cannot reproduce the problem. We can reopen once the requested feedback is provided.

**Closed by raimund-schluessler** 2020-07-02 19:37 UTC
