### ISSUE TITLE
Copy Task

### ISSUE THREAD

**Issue by Sipfox** [nextcloud/tasks#1957] opened 2022-03-30 20:08 UTC
Would it not be possible to add a copy function? I need the tasks to control the workflow of projects. This means that I always have to write the task in the same way.

**Comment by Nightfirecat** [comment] 2022-05-06 20:23
I think this is a duplicate of #264

**Comment by joshtrichards** [comment] 2024-01-21 01:54
Duplicate of #264

**Closed by joshtrichards** 2024-01-21 01:54 UTC
