### ISSUE TITLE
[Feature Request] Associate a full task list with a card or project?

### ISSUE THREAD

**Issue by refutationalist** [nextcloud/tasks#1767] opened 2021-09-06 09:24 UTC
I'm honestly not certain if this belongs here or in Deck, but while other things are being figured out, would it be possible to associate task lists with projects as one can do with files and conversations?   While that may not be fully what is required, it would get my organization pretty much what we need to get the best out of tasks and deck.

**Comment by raimund-schluessler** [comment] 2021-12-07 08:59
Duplicate of https://github.com/nextcloud/tasks/issues/534.

**Closed by raimund-schluessler** 2021-12-07 08:59 UTC
