### ISSUE TITLE
Trying to access array offset on value of type null at /3rdparty/scssphp/scssphp/src/Compiler.php#3387

### ISSUE THREAD

**Issue by acsfer** [nextcloud/tasks#1260] opened 2020-10-10 08:31 UTC
- NC 19.0.4
- PHP 7.4.11
- Tasks 0.13.3

```
{
  "reqId": "VoADKXTwQGp5XwgMeFBx",
  "level": 3,
  "time": "2020-10-10T10:26:41+02:00",
  "app": "PHP",
  "method": "GET",
  "url": "/apps/tasks/",
  "message": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type null at /3rdparty/scssphp/scssphp/src/Compiler.php#3591",
    "Code": 0,
    "Trace": [
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 3591,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 3429,
        "function": "extractInterpolation",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 3424,
        "function": "compileValue",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 3448,
        "function": "compileValue",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2321,
        "function": "compileValue",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1394,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2249,
        "function": "compileBlock",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1394,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2249,
        "function": "compileBlock",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1394,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2249,
        "function": "compileBlock",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 4234,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2067,
        "function": "importFile",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2233,
        "function": "compileImport",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 4234,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2067,
        "function": "importFile",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 2233,
        "function": "compileImport",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 1750,
        "function": "compileChild",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 394,
        "function": "compileChildrenNoReturn",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/3rdparty/scssphp/scssphp/src/Compiler.php",
        "line": 248,
        "function": "compileRoot",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/lib/private/Template/SCSSCacher.php",
        "line": 329,
        "function": "compile",
        "class": "ScssPhp\\ScssPhp\\Compiler",
        "type": "->"
      },
      {
        "file": "/lib/private/Template/SCSSCacher.php",
        "line": 182,
        "function": "cache",
        "class": "OC\\Template\\SCSSCacher",
        "type": "->"
      },
      {
        "file": "/lib/private/Template/CSSResourceLocator.php",
        "line": 111,
        "function": "process",
        "class": "OC\\Template\\SCSSCacher",
        "type": "->"
      },
      {
        "file": "/lib/private/Template/CSSResourceLocator.php",
        "line": 86,
        "function": "cacheAndAppendScssIfExist",
        "class": "OC\\Template\\CSSResourceLocator",
        "type": "->"
      },
      {
        "file": "/lib/private/Template/ResourceLocator.php",
        "line": 79,
        "function": "doFind",
        "class": "OC\\Template\\CSSResourceLocator",
        "type": "->"
      },
      {
        "file": "/lib/private/TemplateLayout.php",
        "line": 311,
        "function": "find",
        "class": "OC\\Template\\ResourceLocator",
        "type": "->"
      },
      {
        "file": "/lib/private/TemplateLayout.php",
        "line": 217,
        "function": "findStylesheetFiles",
        "class": "OC\\TemplateLayout",
        "type": "::"
      },
      {
        "file": "/lib/private/legacy/OC_Template.php",
        "line": 185,
        "function": "__construct",
        "class": "OC\\TemplateLayout",
        "type": "->"
      },
      {
        "file": "/lib/public/AppFramework/Http/TemplateResponse.php",
        "line": 166,
        "function": "fetchPage",
        "class": "OC_Template",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 124,
        "function": "render",
        "class": "OCP\\AppFramework\\Http\\TemplateResponse",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/App.php",
        "line": 137,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->"
      },
      {
        "file": "/lib/private/Route/Router.php",
        "line": 297,
        "function": "call_user_func"
      },
      {
        "file": "/lib/base.php",
        "line": 1011,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/lib/private/Log/ErrorHandler.php",
    "Line": 91,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0",
  "version": "19.0.4.2",
  "id": "5f81705d9810f"
}
```

**Comment by raimund-schluessler** [comment] 2020-10-10 10:35
Duplicate of #1251.

**Closed** 2020-10-10 10:35 UTC
