### ISSUE TITLE
Calendar is Not Displayed Correctly When Assigning a Date

### ISSUE THREAD

**Issue by hashashin1191** [nextcloud/tasks#1403] opened 2021-01-27 12:36 UTC
### Steps to reproduce
1. Click a task.
2. Click start or due time.
3. Click the calendar icon to open the calendar.

### Expected behaviour
The calendar is not overlapped.

### Actual behaviour
The calendar is overlapped with the task list. I will have to zoom out to 70% to see Sunday.

## Server configuration detail

**Operating system:** Linux 5.9.13-postmarketos-qcom-msm8974 #1 SMP PREEMPT Mon Dec 14 08:37:25 UTC 2020 armv7l

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.5.8

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, json, mbstring, openssl, pcntl, PDO, posix, standard, SimpleXML, sqlite3, xml, xmlwriter, zip, mysqlnd, xmlreader, mysqli, pdo_mysql, apcu, imagick, Zend OPcache

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older version.

**Where did you install Nextcloud from:** Nextcloud official download page.

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - audioplayer: 3.0.0
 - bookmarks: 4.0.8
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - checksum: 1.0.1
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - news: 15.1.1
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - passwords: 2020.12.2
 - photos: 1.2.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - activity
 - admin_audit
 - encryption
 - federation
 - files_trashbin
 - sharebymail
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```php
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***""
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.4.0",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "default_language": "ja_JP",
    "default_locale": "ja_JP",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

**Operating system:** openSUSE 15.2

## Logs

<details><summary>Web server error log</summary>

```
(No error occurred.)
```
</details>

<details><summary>Nextcloud log</summary>

```
(Not logged.)
```
</details>

<details><summary>Browser log</summary>

(I don't know how to get it. I will paste it in need.)
</details>

## Screenshot
![Screenshot from 2021-01-27 20-05-53](https://user-images.githubusercontent.com/75371007/105991852-36790e80-609c-11eb-9bd1-4f1a97cc1bef.png)

**Comment by raimund-schluessler** [comment] 2021-01-27 13:11
Duplicate of #935.

**Closed by raimund-schluessler** 2021-01-27 13:11 UTC
