### ISSUE TITLE
Duplicate List and/or List template

### ISSUE THREAD

**Issue by odyn** [nextcloud/tasks#2400] opened 2023-11-25 23:32 UTC
### Is your feature request related to a problem? Please describe.

I'm working for a nonprofit cultural center with a lot of events. And for most events most of the tasks involved are the same. Of course it's very flexible and things may differ. 
I'm chekcing Nextcloud Tasks as a way to organize our team. It looks great, but one thing that I see as problematic is making the same old list of tasks for every event (and we can have several a day).

### Describe the solution you'd like

Either having Templates (dropdown selection?) for Event List (with tasks and subtasks already set there ... just needing List name, dates, team member assignements) or at least an option to duplicate Event list (which I'm guessing should clear out dates and statuses).

### Describe alternatives you've considered

I guess exporting and importing Lists might work. But it's not a user friendly solution.

**Comment by dartcafe** [comment] 2023-11-26 15:06
I guess it is a duplicate of #121

**Comment by raimund-schluessler** [comment] 2023-12-01 18:15
> I guess it is a duplicate of #121

I would say so too. Closing.

**Closed by raimund-schluessler** 2023-12-01 18:15 UTC
Labels: enhancement, 0 - to triage
