### ISSUE TITLE
Tasks details don't disappear as they used to and they cover the task list rendering the app unusable on a phone

### ISSUE THREAD

**Issue by elpraga** [nextcloud/tasks#33] opened 2017-01-11 19:10 UTC
### Steps to reproduce
1. Open the tasks app in chrome or Firefox
2. Try to see the tasks list

### Expected behaviour
When opening the app the list of tasks appear. Clicking on a tasks slides open the details. When -> is pressed, the details slide away.

### Actual behaviour
There is no way to hide the details and they cover almost all screen.

### Server configuration
**Lubuntu 16.04**

**Apache**

**SQLite 3**

**7 something - the default**

**11.0.0.10** (see Nextcloud admin page)

**Tasks version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**
Yes
**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by elpraga** [comment] 2017-01-13 19:02
I couldn't find any relevant logs, but please let me know if I can provide any. 
BTW, on desktop, the -> button doesn't hide task's details either.

Were anybody able to reproduce this behavior?

**Comment by korelstar** [comment] 2017-01-13 19:36
For me, the arrow `->` works correctly (i.e. task details disappear then).
I've tested this with Nextcloud 10.0.2 on the server, and Firefox ESR 45.6.0 on the Desktop as well as Lightning 4.4.1/Chrome WebView 55.0.2883.91 under Android 6.0.1.

With "logs", do you mean the javascript console? This should be the first source for more information.

**Comment by elpraga** [comment] 2017-01-13 19:43
Does anyone have a chance to try it on NextCloud 11? It is not working anywhere for me. I even tried downloading the newest git version.

I saw the logs on the administrator page and I found no mention of tasks app.

Is there something else u could provide? If yes, please let me know how to get it.

**Comment by korelstar** [comment] 2017-01-13 19:46
Please have a look into the javascript console of your browser. On Firefox press CTRL+SHIFT+J.

**Comment by elpraga** [comment] 2017-01-13 19:50
Ok.lll do it when I get home. It's there something specific I should look for? ..I have no idea about Java script... 
In any case, I'll check if I get any info when I press the -> button.

**Comment by korelstar** [comment] 2017-01-13 20:05
Please check if there are any errors.

**Comment by raimund-schluessler** [comment] 2017-01-13 20:27
I cannot reproduce this problem with with Nextcloud 11.0.0. Neither using the latest Firefox 50.1.0 nor with the latest Chrome 55.0.2883.87. The task details disappear when I click on the arrow as well as when I click somewhere in the app.

Could you please specify under what circumstances this problem occurs? In the title it says "phone" but in the text you write Firefox and Chrome. Please also give the versions you are using.

**Comment by elpraga** [comment] 2017-01-13 21:00
Ok, I have some info from Chromium - desktop version. I cleared the cache before trying again. 
Chromium Versión 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04

```
moment-with-locales.js?v=167335c…:282 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Regular.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Regular.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Light.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Light.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Semibold.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Semibold.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Regular.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Light.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
:1943/apps/tasks/#/collections/all:1 Failed to decode downloaded font: https://mycloud.com/themes/Sevilla/core/fonts/OpenSans-Semibold.woff
:1943/apps/tasks/#/collections/all:1 OTS parsing error: invalid version tag
Failed to parse SourceMap: https://mycloud.com/apps/tasks/js/vendor/angular-route/angular-route.min.js.map
Failed to parse SourceMap: https://mycloud.com/apps/tasks/js/vendor/angular-animate/angular-animate.min.js.map
Failed to parse SourceMap: https://mycloud.com/apps/tasks/js/vendor/angular-sanitize/angular-sanitize.min.js.map
Failed to parse SourceMap: https://mycloud.com/apps/tasks/js/vendor/angular/angular.min.js.map
Failed to parse SourceMap: https://mycloud.com/core/vendor/jquery/dist/jquery.min.map
```

**Comment by elpraga** [comment] 2017-01-13 21:11
My phone is Huawei Y6II running Android 6.0.1.  Google Chrome 55.0.28893.91

**Comment by elpraga** [comment] 2017-01-13 21:22
I managed to solve the font errors, I use a custom theme, and the fonts were not loaded from the core folder, so I moved copied the `fonts` folder into my theme folder.

**Comment by elpraga** [comment] 2017-01-13 21:22
Can I provide you with some more information?

**Comment by raimund-schluessler** [comment] 2017-01-13 21:41
Nothing of the error log seems to be related to the problem. Can you please try disabling your custom theme.

**Comment by elpraga** [comment] 2017-01-13 21:49
OK, 
changing back to default theme fixed the problem. Good!  But what could be wrong? I only wanted to replace the background image and change the logo on a login page.

I didn't do any wild changes to the theme, I used `default.php` from the example and coppied the img folder from the original `core` folder.

**Comment by raimund-schluessler** [comment] 2017-01-13 23:17
I can't really tell what's wrong without having a look at the theme. If you would send me your modifications, I would be willing to have a look.

Since the error seems to be not related to Tasks I am closing this issue.

**Closed by raimund-schluessler** 2017-01-13 23:17 UTC

**Comment by elpraga** [comment] 2017-01-14 19:49
Thank you @raimund-schluessler ! Thant would be nice, I would really appreciate it, because I followed the instructions at [admin documentation](https://docs.nextcloud.com/server/11/developer_manual/core/theming.html) and copied the example theme into my theme directory. I added the `fonts` and `js` directories trying to fix the issue with __Tasks app__.

In my opinion, simple changing of a theme should not render an app unusable. I might have stumbled upon a more serious issue. 

Thank you for having a look at it.

**Comment by raimund-schluessler** [comment] 2017-01-14 20:28
@elpraga The problem is that your theme overwrites the properties of ```#app-sidebar``` which supersedes the changes of the Tasks app to this element. As a quick solution it would be sufficient to remove the file ```Sevilla\core\css\apps.css``` or to remove the lines 438:455 of the said file.

As a more save option I guess I have to change the naming of app-sidebar to something else or don't overwrite its properties. I opened an issue for that: #35.

**Comment by elpraga** [comment] 2017-01-14 20:39
Thank you @raimund-schluessler ! I also think that having a fail safe solution would be better in order to avoid randomly rendering Tasks app unusable by a simple theme change. 

Thank you for your help!

**Comment by elpraga** [comment] 2017-01-16 20:16
Thank you @raimund-schluessler ! I can confirm that your fix works.  

Thank you so much for your quick reply and fix!

It would be great if you could finish [#35](https://github.com/nextcloud/tasks/issues/35) so that things cannot get randomly messed up simply by following the documentation and using slightly modified example theme.
