### ISSUE TITLE
Date and Time fields do not fit on smaller screen like cromebook / tablet

### ISSUE THREAD

**Issue by xonlinedevelopment** [nextcloud/tasks#1457] opened 2021-03-23 20:37 UTC
### Steps to reproduce
Get a cromebook, tablet or set your browser to a smaller size
Login to Nextcloud, Enter Tasks, Create a Task, Set Date and Time.

### Expected behaviour
The date field and the time field should be displayed correctly

..suggestion.... maybe you can make them flow, or use a modal to bring them to front...

### Actual behaviour
The datefield shows only half, only Wo. Th, Fr, Sa are visible

### Server configuration

**Operating system**:  Centos 7

**Web server:** Apache

**Database:** MySQL / MariaDB

**PHP version:** 7.0

**Nextcloud version:** 18.02

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.

**List of activated apps:**
Tasks, Notes, Quicknotes, Calendar, Rainloop, Bookmarks, Flowupload, Talk


### Client configuration
**Browser:**   Chrome

**Operating system:**
Windows 10, Windows 2012, Crome OS ( all same result )

**Comment by raimund-schluessler** [comment] 2021-03-23 21:17
I think what you describe is a duplicate of https://github.com/nextcloud/tasks/issues/935. If you meant to report a different problem, please provide a screenshot of the issue.

**Closed by raimund-schluessler** 2021-03-23 21:17 UTC

**Comment by xonlinedevelopment** [comment] 2021-03-23 23:09
![afbeelding](https://user-images.githubusercontent.com/43137619/112230505-3a0cba00-8c35-11eb-97fd-2eed1aa035bc.png)
![afbeelding](https://user-images.githubusercontent.com/43137619/112230519-3f6a0480-8c35-11eb-84b3-5a9698b95ff0.png)

**Comment by raimund-schluessler** [comment] 2021-03-24 08:13
Yes, this is a duplicate.
