### ISSUE TITLE
feature request - Attachments

### ISSUE THREAD

**Issue by rtloeffler** [nextcloud/tasks#1303] opened 2020-10-19 19:04 UTC
### Steps to reproduce
1. Open task
2. Select attachment from mobile device or local storage on nextcloud
3. Sync attachments nextcloud to mobile device 

### Expected behaviour
The attachment should sync between devices

### Actual behaviour
feature request

**Comment by raimund-schluessler** [comment] 2020-10-19 19:42
Duplicate of #91.

**Closed by raimund-schluessler** 2020-10-19 19:42 UTC
