### ISSUE TITLE
[Question] Are shared Task lists surpose to auto update?

### ISSUE THREAD

**Issue by swdee** [nextcloud/tasks#1899] opened 2022-01-04 04:46 UTC
Given a Task list that has been shared with another user who can also edit the list.  If User A makes a change to the task list (eg: completes a task, updates its status, updates percentage complete etc) these changes are not updated on User B's screen unless they refresh the browser/page.

Is this manual refresh of the task list to get the changes the expected behaviour, or should these changes be pushed to all shared users and screen auto update? 

Is it possible to make them auto update across all shared users?  Any hints as to how that could be achieved?

**Comment by raimund-schluessler** [comment] 2022-01-04 09:14
No, the app does not automatically update when tasks are changed outside of it (e.g. by other clients or users). You will have to refresh the page to get the current state. This is a duplicate of #915.

**Closed by raimund-schluessler** 2022-01-04 09:14 UTC
