### ISSUE TITLE
Not editing Task list (Name and color)

### ISSUE THREAD

**Issue by Leprazoriy** [nextcloud/tasks#1292] opened 2020-10-16 19:41 UTC
### Steps to reproduce
1. Open the Tasks app
2. Create a new task list
3. Try editing the created task list

### Expected behaviour
Editing the name of the task list and the selected color

### Actual behaviour
Nothing happens when the edit button is pressed!

### Server configuration

**Operating system**:
Linux Ubuntu 18.0.4

**Web server:**
Apache2 + NGINX Proxy

**Database:**
MariaDB

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
19.0.3 and 19.0.4

**Tasks version:** (see Nextcloud apps page)
0.13.4

**Updated from an older Nextcloud or fresh install:**
19.0.3 fresh install, 19.0.4 updated from 19.0.3

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```

**List of activated apps:**
Accessibility, Activity, Audio Player, Audio Player - ID3 Editor (add-on), Brute-force settings, Calendar, Collaborative tags, Comments, Contacts, Contacts Interaction, Deleted files, Federation, File sharing, First run wizard, Group folders, Log Reader, Monitoring, Nextcloud announcements, Notes, Notifications, ONLYOFFICE, Password policy, PDF viewer, Photos, Privacy, Recommendations, Right click, Share by mail, Support, Talk, Tasks, Text, Theming, Update notification, Usage survey, Versions, Video player

### Client configuration
**Browser:**
Chrome, Firefox, Opera

**Operating system:**
Windows 10

**Comment by raimund-schluessler** [comment] 2020-10-17 05:52
Duplicate of #1276, fixed in master. Will come with the next patch release soon.

**Closed** 2020-10-17 05:52 UTC
