### ISSUE TITLE
[Feature Request] Rich text for task Description

### ISSUE THREAD

**Issue by Oleg-dM** [nextcloud/tasks#155] opened 2018-03-29 13:41 UTC
Hi,

I would like to use Tasks as a note keeping system (like Google Keep).
It looks like the perfect tool but the Description pane lacks some basic formatting features.
It would make the tool so much more powerful if possible to format the notes with at least bold/underlining and may be numbered list ?

If anyone has already started to work on such improvement, I am open to contribute as well.

Thanks !

**Comment by raimund-schluessler** [comment] 2018-04-11 07:53
I think this is a duplicate of #76. Supporting markdown in the notes field would give you formating options. Feel free to reopen, in case you meant something else.

**Closed by raimund-schluessler** 2018-04-11 07:53 UTC
