### ISSUE TITLE
Adding date with time does not work correctly

### ISSUE THREAD

**Issue by maxlStone** [nextcloud/tasks#1849] opened 2021-11-14 08:07 UTC
### Steps to reproduce
1. Create a task
2. Add a date (not today) and also a time to it
3. Click okay and the date changes to today with the configured time

### Expected behaviour
Date should be as configured

### Actual behaviour
Date changes to today and the time setting is correctly taken

### Server configuration

**Operating system**:
Debian GNU/Linux 10. 5.10.63-v8+ (aarch64)

**Web server:**

**Database:**
mysql, 10.3.31

**PHP version:**
7.3.31

**Nextcloud version:** (see Nextcloud admin page)
20.0.12.1

**Tasks version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**
Updated from an older version

**Signing status:**

No errors have been found.

**List of activated apps:**

**Nextcloud configuration:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
local. 2x btrfs hdd
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox 94
**Operating system:**
elementary OS 6 Odin, Ubuntu 20.04.3 LTS, Linux 5.11.0-38-generic
**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

```

**Comment by raimund-schluessler** [comment] 2021-11-14 08:24
Duplicate of https://github.com/nextcloud/tasks/issues/1816. Fix comes with next release.

**Closed by raimund-schluessler** 2021-11-14 08:24 UTC
