### ISSUE TITLE
Use Nextcloud Flow to add task

### ISSUE THREAD

**Issue by geonom** [nextcloud/tasks#2408] opened 2023-12-10 14:58 UTC
### Describe the solution you'd like

I would like to easily create tasks, e.g. when a document is uploaded that contains "Draft" in the filename, create a task with an end date two weeks in the future as implement feedback and finalize draft.

### Describe alternatives you've considered

Manually adding tasks, but that is not as reliable.

**Comment by raimund-schluessler** [comment] 2024-01-10 21:14
Duplicate of #971.

**Closed by raimund-schluessler** 2024-01-10 21:14 UTC
Labels: enhancement, 0 - to triage
