### ISSUE TITLE
update only when clicking on tasks icon in the app list

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/tasks#1896] opened 2021-12-24 06:00 UTC
Nextcloud 23, Task App

I have installed tasks app and test it with two users in two browsers. If i create a task or click the checkbox to close a task i get not an update for the other user.  Only if if i click at the tasks icon in the app list above it is updated.

**Comment by raimund-schluessler** [comment] 2021-12-26 08:53
Duplicate of https://github.com/nextcloud/tasks/issues/915.

**Closed by raimund-schluessler** 2021-12-26 08:53 UTC
