### ISSUE TITLE
After Upgrade to 12.0 Task List empty but still shows on Client Devices

### ISSUE THREAD

**Issue by bstin** [nextcloud/tasks#909] opened 2020-03-08 15:09 UTC
### Steps to reproduce
1. Upgrade to 12.0
2. Look at Web interface and see that Task List is emtpy
3. On client devices (Evolution Linux Desktop / Reminders iOS) see task are still present

### Expected behaviour
Should show task on Web Interface

### Actual behaviour
Blank

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 12.0.1

**Tasks version:** (see Nextcloud apps page) 12.0

**Comment by bstin** [comment] 2020-03-08 15:11
Addendum: 

If I add a "New List" on Web Interface it will appear on Client devices, but as soon as I add a task from Client Device (ie. Evolution), the list disappears from Web Interface but continues to show on Client Devices.

**Comment by bstin** [comment] 2020-03-08 15:16
Addendum: 

It also seems to have deleted ALL my calendars? 

Is there a way to downgrade. Suddenly no Calendars are showing up on any device? 

How is this possible?

**Comment by raimund-schluessler** [comment] 2020-03-08 15:19
Duplicate of https://github.com/nextcloud/tasks/issues/908, PR is in #911, will be released with 0.12.1 soon.

Your calendars were not deleted by the Tasks app for sure. It is just a client and #908 prevented the app from loading correctly. It didn't lead to a deletion of data.

**Closed by raimund-schluessler** 2020-03-08 15:19 UTC

**Comment by raimund-schluessler** [comment] 2020-03-09 12:20
I suppose everything works again with v0.12.1?

**Comment by pweiden** [comment] 2020-03-09 12:29
From my point of view, everything is working again with 0.12.1 as it was with 0.11.3. Thanks for the quick fix!
