### ISSUE TITLE
Drag and drop broken

### ISSUE THREAD

**Issue by phetish** [nextcloud/tasks#78] opened 2017-05-18 21:02 UTC
### Steps to reproduce
1. Using Chrome or MS Edge open Tasks App
2. Click and drag a task to either reorder within a list of tasks or drag to an existing list.
3. Notice that the task does not move.

### Expected behaviour
The task should move to the position in the list of tasks or move to the selected Task List. 

### Actual behaviour
Nothing happens - unless you are using Firefox.  In Firefox, the drag and drop interface works correctly when moving to a different Task List or moving a Task to become a subtask for an existing Task, but it does not allow you to reorder tasks.

**Comment by 4oo4** [comment] 2017-05-23 21:37
That's interesting, I've had the same issue with drag/drop, but for me it works in Chrome but not in Firefox (for Windows 7 as well as Ubuntu 16.04).

**Comment by SvenLuebke** [comment] 2017-06-07 20:30
I have the same issue with Chrome: Moving a window does nothing. It's working flawlessly in Firefox (both Win7 x64).

**Comment by Alys** [comment] 2017-06-13 22:22
Dragging and dropping tasks to reorder them in markdown task lists also fails in Vivaldi 1.6.689.46 (Stable channel) (64-bit) on Ubuntu 16.04.1 LTS. No errors appear in the JavaScript console.

It succeeds in Firefox 53 on the same machine.

**Comment by wouck** [comment] 2017-06-27 01:57
It doesn't work in Chrome 58.0.3029.110 (64-bit)

**Comment by NesterovMaxim** [comment] 2017-06-27 19:55
It doesn't work in chromium-based browser(Yandex browser)

**Comment by vitobotta** [comment] 2017-12-09 17:27
I see that for some of you it works with Firefox, but for me it doesn't - I am using Firefox Quantum 57. I know it's been a while so I was wondering whether there was an update about this? Thanks!

**Comment by 4oo4** [comment] 2017-12-09 18:17
@vitobotta What OS are you using? I hadn't tried this since the update to Quantum, but it still works for me using Firefox 57.0.1 in Ubuntu 16.04.

**Comment by vitobotta** [comment] 2017-12-09 18:55
Hi! I'm on Ubuntu 17.10. I haven't tried with a previous version unfortunately so I don't know. So, on your system you can just rearrange tasks with drag and drop as expected?

**Comment by 4oo4** [comment] 2017-12-09 19:16
@vitobotta  Yep, but only using Firefox. It worked for me both before and after the Quantum update, but it has never worked for me in Chromium (haven't tried regular Chrome, but I don't think that would make a difference). Maybe there's something different with the Firefox builds for 16.04 and 17.10?

**Comment by vitobotta** [comment] 2017-12-09 19:18
Weird. I'll see if I can try it in 16.04 in a VM, thanks! :)

**Comment by techworm21** [comment] 2018-02-26 21:10
Do we have a fix for this? 

Not working with Chrome on a MacBook Pro, but with Firefox it works.

**Comment by cptMikky** [comment] 2018-03-16 14:00
Doesn't work for me in neither Firefox 59.0 nor in Chromium 65.0.3325.162 @ Arch Linux, and also in Chrome 65.0.3325.162 @ Win10.

Strangely it **does** work in Edge 38 @ Win10.

**Comment by mr-intj** [comment] 2018-04-20 17:55
On my Debian Stretch (x64):

* Firefox ESR 52.6.0 (64-bit) - **works**
* Chrome 64.0.3282.140 (Official Build) (64-bit) - **doesn't work**

**Comment by mr-intj** [comment] 2018-05-14 16:58
@raimund-schluessler, et. al. - I'd like to work on fixing this. It would same me some time if someone could point me at the code involved, along with any additional information you may have?

Thanks!

**Comment by CamZie** [comment] 2019-04-23 14:35
Hello everyone, do you have any updates on this? The problem still exists in Chrome. Many thanks!

**Comment by raimund-schluessler** [comment] 2019-04-23 17:43
This issue is the last blocking issue before releasing the vue.js rewrite with v0.10.0. I plan on fixing this is #236, but it is a bit tricky. I didn’t find the perfect drag and drop library for Tasks yet. Also see https://github.com/nextcloud/tasks/milestone/1 for what is left to do.

If you feel like it, you can also test the v0.10.0 alpha versions in #270. There it’s possible to change the calendar in the details view. But dnd is not yet implemented, so you can’t move subtasks (a regression for Firefox users at least).

**Closed** 2019-05-06 12:42 UTC
Labels: bug, vue
