### ISSUE TITLE
Lack of Setting Due Time

### ISSUE THREAD

**Issue by vatolin** [nextcloud/tasks#2651] opened 2024-08-16 07:46 UTC
### Steps to reproduce

I mean to remember that one could give a task a specific due time when creating a new task in the web frontend of NC in the browser. But now I can only define the due date but not the due time.

Per default the checkbox "whole day" is activated. Inactivating "whole day" does not let appear a time setting feature.

Am I wrong? Or is the lack of due time a feature but not a failure?

NC 29.0.4
Tasks 0.16.0

### Expected behavior

There should be a time setting feature.

### Actual behaviour

No time setting feature is availabe at the web GUI.

### Tasks app version

0.16.0

### CalDAV-clients used

Web GUI in Firefox 129.0.1

### Browser

Firefox 129.0.1

### Client operating system

MacOS, Windows

### Server operating system

Debian

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

Other

### Nextcloud version

29.0.1

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by raimund-schluessler** [comment] 2024-08-16 08:08
Duplicate of https://github.com/nextcloud/tasks/issues/2585. This will be fixed with 0.16.1

**Closed by raimund-schluessler** 2024-08-16 08:08 UTC
Labels: bug
