### ISSUE TITLE
Category "search as you type" display gibberish instead of existing categories

### ISSUE THREAD

**Issue by googol42** [nextcloud/tasks#604] opened 2019-09-11 05:43 UTC
### Steps to reproduce
1. Create new Task via Web
2. Edit Task -> Start to add a category to the task

### Expected behaviour
While typing existing categories should be displayed

### Actual behaviour
A serialisation of a json object is shown. Existing categories are **not** shown.

<img src="https://user-images.githubusercontent.com/9155562/64670740-62273480-d466-11e9-8d4d-4045dff1196e.png" width="300">

## Server configuration detail

**Operating system:** Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64

**Webserver:** Apache/2.4.39 (Unix) (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.1.32
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, restrictdocroot, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, apcu, gnupg, imagick, zip, phalcon, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - calendar: 1.7.1
 - camerarawpreviews: 0.7.0
 - checksum: 0.4.3
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - gallery: 18.3.0
 - gpxpod: 4.0.5
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - phonetrack: 0.5.2
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - tasks: 0.11.1
 - text: 1.0.2
 - twofactor_backupcodes: 1.5.0
 - unsplash: 1.1.3
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - fulltextsearch
 - privacy
 - recommendations
 - support
 - survey_client
 - systemtags
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "***REMOVED***",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "theme": "",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable"
}
```
</details>

**Comment by raimund-schluessler** [comment] 2019-09-11 05:46
Duplicate of #416, will be closed with 0.11.2 which is coming soon.

**Closed by raimund-schluessler** 2019-09-11 05:46 UTC
