### ISSUE TITLE
Set a personal start view

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/tasks#637] opened 2019-09-24 10:33 UTC
It would be nice to set the start view: Important, Today, Week, All
Currently tasks starts always with the All view.

Btw: What's the difference between All and Current?
![grafik](https://user-images.githubusercontent.com/24530680/65504500-6ff9a280-dec7-11e9-8df3-fd73ec216591.png)

**Comment by raimund-schluessler** [comment] 2019-09-24 10:45
Duplicate of #80. And I am not very keen on introducing a new setting.
But we could remember the last view, similar as in #615.

And the Current view does not show tasks which have not begun yet (i.e. a start date in the future).

**Closed by raimund-schluessler** 2019-09-24 10:45 UTC
