### ISSUE TITLE
Hide canceled tasks

### ISSUE THREAD

**Issue by dargmuesli** [nextcloud/tasks#1417] opened 2021-02-12 13:07 UTC
### Steps to reproduce
1. Cancel a task
2. Look at the "All" or "Current" tasks list

### Expected behaviour
Canceled tasks should not be listed without clicking "Show canceled tasks" or something alike.

### Actual behaviour
Keeping an overview over all open tasks is difficult as canceled tasks are shown just as open tasks within the "All" or "Current" tasks list.

### Server configuration
**Nextcloud version:** 20.0.4
**Tasks version:** 0.13.6

**Comment by raimund-schluessler** [comment] 2021-02-12 13:18
Duplicate of #1060

**Closed by raimund-schluessler** 2021-02-12 13:18 UTC

**Comment by dargmuesli** [comment] 2021-02-12 13:20
Uh, sorry, first only searched for "aborted" and "interrupted" before writing this issue an actually changing my Nextcloud's language to English and finding it's called "canceled".
