### ISSUE TITLE
Add option to hide task lists

### ISSUE THREAD

**Issue by schiessle** [nextcloud/tasks#2402] opened 2023-11-29 17:43 UTC
### Is your feature request related to a problem? Please describe.

I have a lot of shared calendars and Deck board from my colleagues. All full with tasks not relevant for me. This makes the task app quite crowded and not really usable for me.  Especially the "Today", "Week", "All",... views contain a lot of entries not relevant to me but also the large list of calendars on the sidebar lead to a quite noisy interface. 

### Describe the solution you'd like

Have a option ho hide/ignore task lists so that I only see the tasks which are relevant for me

**Comment by raimund-schluessler** [comment] 2023-12-01 18:14
I would say this is a duplicate of #1858. Although "Hide" and "Archive" have slightly different meaning, the workflow and result would be the same: a task list is hidden from the view.

**Closed by raimund-schluessler** 2023-12-01 18:14 UTC
Labels: enhancement, 0 - to triage
