### ISSUE TITLE
Priority - change on task list view

### ISSUE THREAD

**Issue by smokinjo** [nextcloud/tasks#2356] opened 2023-09-29 12:55 UTC
The priority seems to be able to turned on and of(mine is either red or white).

The need to go inside the task adds the extra step to change it.

The three dots for "add subtask or delete task".   Whiile these options are avaialble inside the task details page, these 3 dots were likely added to save that extra step and allow those two options to be executed with out going inside the task page.

   This same menu style could be used to select the priority level.  This would save that extra step of going inside the task page to change the priority.

-------------------
              The priority is indicated by the color of the star on the right side of the task.

Clicking the star changes the priority. For a fine control of the priority, you have to open it.

_Originally posted by @raimund-schluessler in https://github.com/nextcloud/tasks/issues/2353#issuecomment-1740808065_

**Comment by raimund-schluessler** [comment] 2023-09-29 13:38
Duplicate of #2353.

Your proposal still takes two steps to change the tasks priority. One click to open a menu, one click to set the priority. This is what we have already. One click to open the sidebar, another click to adjust the priority.

The three dots with "add subtask" are there, because they only make sense there. "Delete task" is indeed duplicated from the sidebar, because we have a delete option for many other apps at this place. And just like many other apps, adjusting the details of the task is done in the sidebar. If we start putting options in the three dot menu, there is no reason why we should priority there, but not list belonging, start or due date as well. We want to keep the main view clear, so you find the details in the sidebar.

**Closed by raimund-schluessler** 2023-09-29 13:38 UTC

**Comment by smokinjo** [comment] 2023-09-29 14:09
The idea is not to add the priority options to the 3 dots.   This menu seems ot related at creating and deleting tasks.

My idea is to just turn the star into a menu with 9 options(like the 9 levels of priority).

I also now realized that the task details is open, so I also see your point about people able to change the priority.

An enhancement than would be to improve the level of clarity when reading the priority level of the stars.  Stars represent 3 levels fo priority.   

The level number could be added to add an extra layer of clarity when reading the priority level.
