### ISSUE TITLE
checklists

### ISSUE THREAD

**Issue by loziniak** [nextcloud/tasks#132] opened 2017-12-04 12:44 UTC
Hi, is it possible to implement checklists as in this image (screenshot from OpenTasks Android app):
https://lh5.ggpht.com/jXb5dlQs_i8SpAlbS4lrkoRW8KJNngDC2VGU6CmzUcJou7MDy7kEvqZsv5cJFK_so0o=h900

**Comment by danopz** [comment] 2017-12-04 13:03
Duplicate of #76

**Closed** 2017-12-04 13:46 UTC
