### ISSUE TITLE
[Feature Request] Export all tasks && convert to pdf or print

### ISSUE THREAD

**Issue by k-0** [nextcloud/tasks#1678] opened 2021-07-09 12:50 UTC
I miss the function to export (all) tasks. I can only download each task separate.
The possibility to export the task(s) to a pdf-file or print them would be very nice!

**Comment by raimund-schluessler** [comment] 2021-07-09 12:53
Duplicate of https://github.com/nextcloud/tasks/issues/163 and https://github.com/nextcloud/tasks/issues/74

**Closed by raimund-schluessler** 2021-07-09 12:53 UTC
