### ISSUE TITLE
Due date calendar clipped on small screens

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/tasks#1395] opened 2021-01-19 04:02 UTC
### Steps to reproduce
1. Create task
2. Open due date calendar menu
3. Narrow screen

### Expected behaviour
The calendar should be fully visible and not clipped

![image](https://user-images.githubusercontent.com/8503756/104986407-59932680-59e9-11eb-9f2f-8b7bfc0b57fd.png)

### Actual behaviour
The menu is clipped by the task stack

![image](https://user-images.githubusercontent.com/8503756/104986421-60ba3480-59e9-11eb-93f3-15f84bc272a6.png)

The first image above is actually at a narrower resolution. I think below 400px, a media query kicks in that aligns the calendar to its left side rather than its right side. I think a fix would just be to apply these styles at a much wider resolution, or always.

I can include logs, but I don't think that is required for such a css bug. Sorry for being lazy.

### Client configuration
**Browser:** Reproduced in latest firefox and chromium

**Operating system:** Arch Linux

**CalDAV-clients:** N/A

**Comment by raimund-schluessler** [comment] 2021-01-19 06:50
Thanks for the detailed report. It's a duplicate of #935.

**Closed** 2021-01-19 06:51 UTC

**Comment by MarcelRobitaille** [comment] 2021-01-19 15:16
Sorry about that. I guess I used the wrong keywords when searching if it had been reported before.
