### ISSUE TITLE
Feature Request: Repeating tasks and automated reset of completed tasks please. 

### ISSUE THREAD

**Issue by Daveladd** [nextcloud/tasks#126] opened 2017-11-23 16:35 UTC
Would it be possible to add functionality to the Tasks app that would allow us to tag certain tasks as repeating? Say I need a task to be done 3 times a day every day, or once everyday, once a week etc. Or could there be a way to tag a task so if it were marked as completed it could automatically reset at some time interval such as the one above. Great app and I would like to find multiple dynamic ways to utilize it. Thank you.

**Comment by xraMsamohT** [comment] 2017-11-27 15:15
Duplicate of #34.

**Closed** 2017-11-27 16:18 UTC
