### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by shgysk8zer0** [nextcloud/tasks#913] opened 2020-03-08 15:55 UTC
### Steps to reproduce
Load page

### Expected behaviour
Should show task lists, etc.

### Actual behaviour
Blank page (shows normal page stuff)
[![screenshot](https://i.imgur.com/ksuDN50l.jpg)](https://i.imgur.com/ksuDN50.jpg)

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (fpm-fcgi)

**Database:** mysql 10.4.12

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.0.0
 - announcementcenter: 3.7.0
 - appointments: 1.1.1
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - audioplayer_editor: 0.2.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - checksum: 0.4.4
 - circles: 0.18.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - cookbook: 0.5.7
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_downloadactivity: 1.7.0
 - files_frommail: 0.3.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.7
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.0
 - gpxpod: 4.1.1
 - group_everyone: 0.1.4
 - groupfolders: 6.0.1
 - guests: 1.4.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - maps: 0.1.5
 - metadata: 0.11.1
 - news: 14.1.3
 - nextbackup: 19.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - passwords: 2020.3.1
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sharingpath: 0.1.1
 - social: 0.2.101
 - sociallogin: 2.4.4
 - socialsharing_diaspora: 2.0.0
 - socialsharing_email: 2.0.0
 - socialsharing_facebook: 2.0.0
 - socialsharing_twitter: 2.0.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.12.0
 - telephoneprovider: 1.0.3
 - terms_of_service: 1.4.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_admin: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - twofactor_u2f: 5.0.2
 - twofactor_webauthn: 0.1.2
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - bookmarks
 - camerarawpreviews
 - cms_pico
 - cospend
 - data_request
 - dicomviewer
 - encryption
 - event_update_notification
 - external
 - files_external
 - files_lock
 - files_markdown
 - music
 - qownnotesapi
 - twofactor_email
 - user_ldap
 - workflow_pdf_converter

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.kernvalley.us"
    ],
    "htaccess.RewriteBase": "\/",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/cloud.kernvalley.us",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "America\/Los_Angeles",
    "log_rotate_size": 2097152,
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_sendmailmode": "smtp",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "forms",
        "dashboard",
        "dicomviewer",
        "social",
        "files_frommail"
    ],
    "has_rebuilt_cache": true,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
NA
```
</details>

<details><summary>Nextcloud log</summary>

```
[core] Error: InvalidArgumentException: The given object id is invalid at <<closure>>

0. /var/www/html/nextcloud/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php line 103
   OC\Notification\Notification->setObject("dav", "6opmce9o60qmcbb ... m")
1. /var/www/html/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php line 148
   OCA\DAV\CalDAV\Reminder\NotificationProvider\PushProvider->send(Sabre\VObject\Co ... }}, "Nextcloud", [OC\User\User {},OC\User\User {}])
2. /var/www/html/nextcloud/apps/dav/lib/BackgroundJob/EventReminderJob.php line 68
   OCA\DAV\CalDAV\Reminder\ReminderService->processReminders()
3. /var/www/html/nextcloud/lib/private/BackgroundJob/Job.php line 61
   OCA\DAV\BackgroundJob\EventReminderJob->run(null)
4. /var/www/html/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/html/nextcloud/cron.php line 125
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-03-08T08:45:36-07:00
```
</details>

<details><summary>Browser log</summary>

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
New search handler registered search.js:67:12
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
TypeError: "e.shares is undefined"
    Fr uidToColor.js:101
    t calendars.js:274
    t calendars.js:263
    promise callback*t/< calendars.js:263
    l runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    Pr cdav-requests.js:39
    a cdav-requests.js:50
    Rr cdav-requests.js:55
    Rr cdav-requests.js:48
    getCalendars calendars.js:284
    h vuex.esm.js:747
    dispatch vuex.esm.js:438
    dispatch vuex.esm.js:332
    t TheSettings.vue:1
    l runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    te TheSettings.vue:93
    a TheSettings.vue:1
    promise callback*te TheSettings.vue:97
    a TheSettings.vue:1
    promise callback*te TheSettings.vue:97
    a TheSettings.vue:1
    beforeMount TheSettings.vue:1
    beforeMount TheSettings.vue:1
    beforeMount tasks.js:2
    VueJS 16
    <anonymous> principals.js:92
    Webpack 3
vue.runtime.esm.js:1888:12
    VueJS 20
    <anonymous> principals.js:92
    Webpack 3

</details>

**Comment by raimund-schluessler** [comment] 2020-03-08 15:58
Duplicate of #908, was fixed with #911, and released as 0.12.1 to the appstore already. Should show up as update soon.

**Closed by raimund-schluessler** 2020-03-08 15:58 UTC
