### ISSUE TITLE
Combine "all" task list in one long list

### ISSUE THREAD

**Issue by smokinjo** [nextcloud/tasks#2355] opened 2023-09-29 12:50 UTC
OK, I did not see the all view. I did not notice it.

But, this does not do what I was looking for(even though my description was not perfectly clear).

I want to be able to literally combine all the tasks in one list. In order to clarify each item and where it comes from, a column would be created to identify the list that it is on.

This additional column could also be used, maybe at a later improvement, to allow a user to switch the task list that the task is on.

How can this be achieved?

--------------------

              We have the smart list "All". If you don't see it, it's probably disabled. Enable it in the settings on the left bottom.

_Originally posted by @raimund-schluessler in https://github.com/nextcloud/tasks/issues/2354#issuecomment-1740809802_

**Comment by raimund-schluessler** [comment] 2023-09-29 13:44
Duplicate of #2354. @smokinjo Please stop opening new issues for the same feature request. If you want to discuss more, do that in the original issue, please.

I don't see a benefit of removing the section titles i.e. list names and instead move them into a column of the tasks. This just makes it harder to immediately see to which list a task belongs.

And adjusting to which list a task belongs is done in the sidebar, as it is realized for all other properties of the tasks.

If you really want this adjustment, I am afraid you need to implement it yourself. Removing the list names could be done via CSS, showing the in a column would require to adjust the javascript code.

**Closed by raimund-schluessler** 2023-09-29 13:44 UTC

**Comment by smokinjo** [comment] 2023-09-29 14:14
Hello,

Being new to using github, when I saw that you closed the discusison, I figured that you could no longer add comment to it.  So, I created a new conversation.   I'll comment here then.
When looking at the tasks in a long list of tasks, adding the name in a column would, I believe, make it easier, not harder,  to determine which list it belongs to because it would be written right next to the task text.
