### ISSUE TITLE
Category list is everytime empty

### ISSUE THREAD

**Issue by cl4x** [nextcloud/tasks#836] opened 2020-01-28 08:07 UTC
###Steps to reproduce
1. Add a Category on Task
2. On other Task (or subtask) the list of category is everytime empty

### Expected behaviour
The category isnìt global?

### Actual behaviour
The category disappears

### Server configuration
**Operating system**: Debian
**Web server:** Apache
**Database:** MYSQL
**PHP version:** 7
**Nextcloud version:** 17.0.2 (last at the moment)
**Tasks version:** 0.11.3 (last at the moment)
**Updated from an older Nextcloud or fresh install:** update from 16

### Client configuration
**Browser:** Firefox, Chrome, same issue
![nc](https://user-images.githubusercontent.com/47188814/73245870-8ed9af80-41ad-11ea-8d86-191b9f21a136.JPG)

**Comment by raimund-schluessler** [comment] 2020-01-28 08:23
Yes, the category list is not global yet. Duplicate of #792 and tracked in #89.

**Closed by raimund-schluessler** 2020-01-28 08:23 UTC
