### ISSUE TITLE
Calendar window truncated on the left

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#1247] opened 2020-09-27 05:40 UTC
### Steps to reproduce

1. Create a task.
2. Select "Set start date" or "Set due date".
3. Click on the calendar icon.

### Expected behaviour
Displaying the full calendar in the window.

### Actual behaviour
The calendar in the window is truncated on the left side.

![obraz](https://user-images.githubusercontent.com/47037905/94356834-148e6180-0093-11eb-94ff-a58724360f1d.png)

**Nextcloud version:** (see Nextcloud admin page)
20.0.0.RC2

**Tasks version:** (see Nextcloud apps page)
0.13.3

### Client configuration
**Browser:**
Firefox 81.0

**Comment by raimund-schluessler** [comment] 2020-09-27 05:46
Duplicate of #935.

**Closed** 2020-09-27 05:46 UTC
Labels: bug
