### ISSUE TITLE
Trimming the tailed letters in the task name

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#975] opened 2020-04-25 11:17 UTC
### Steps to reproduce

1. Create a new task.
2. Enter a name containing letters, e.g. y or j.

### Expected behaviour
Full visibility of letters (petioles).

### Actual behaviour
The name of the task slightly trims the letters such as: y or j.

![obraz](https://user-images.githubusercontent.com/47037905/80278348-d1038600-86f5-11ea-9ac4-6dcd6b116ac3.png)

**Nextcloud version:** (see Nextcloud admin page)
18.0.3
**Tasks version:** (see Nextcloud apps page)
0.12.1

### Client configuration
**Browser:**
Firefox 75.0
**Operating system:**
Win10

**Comment by raimund-schluessler** [comment] 2020-04-25 17:55
Duplicate of #916, was closed with #917, will be released with the next version.

**Closed by raimund-schluessler** 2020-04-25 17:55 UTC
Labels: design
