### ISSUE TITLE
The requested uri cannot be processed by the script '/nextcloud/index.php')

### ISSUE THREAD

**Issue by hanneschu1z** [nextcloud/tasks#2691] opened 2024-09-24 15:58 UTC
### Steps to reproduce

1. Open the Tasks app.
2.
3.

### Expected behavior

No error in Log

### Actual behaviour

Error in Log: The requested uri(/apps/tasks/css/tasks-store.css) cannot be processed by the script '/nextcloud/index.php')

### Tasks app version

0.16.1

### CalDAV-clients used

Browser

### Browser

Microsoft Edge Version 129.0.2792.52

### Client operating system

Windows 11

### Server operating system

Debian 11

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

29.0.7

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 7.0.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.2
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_accesscontrol: 1.19.1
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - geoblocker: 0.5.15
  - imageconverter: 2.0.2
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.8
  - maps: 1.4.0
  - memories: 7.4.1
  - nextcloud_announcements: 1.18.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - oauth2: 1.17.1
  - onlyoffice: 9.4.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quota_warning: 1.20.0
  - recognize: 7.1.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - side_menu: 3.13.1
  - socialsharing_email: 3.1.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflow_ocr: 1.29.0
  - workflowengine: 2.11.0
Disabled:
  - encryption: 2.17.0 (installed 2.8.1)
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - user_ldap: 1.20.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "78.94.76.185",
            "schulzbox.de",
            "192.168.1.1",
            "nextcloud",
            "192.168.1.2",
            "nextcloud.schulzbox.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.7.1",
        "overwrite.cli.url": "https:\/\/nextcloud.schulzbox.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "versions_retention_obligation": "0, auto",
        "theme": "",
        "default_language": "de",
        "default_phone_region": "DE",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_external_dropbox",
            "files_external_gdrive",
            "whiteboard",
            "video_converter",
            "impersonate"
        ],
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mysql.utf8mb4": true,
        "onlyoffice": {
            "jwt_header": "AuthorizationJwt"
        },
        "maintenance_window_start": 1,
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/var\/www\/html\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.vod.disable": false,
        "memories.gis_type": 1
    }
}
```

### Web server error log

```Text
[Tue Sep 24 00:00:10.257329 2024] [mpm_event:notice] [pid 291142:tid 291142] AH00489: Apache/2.4.62 (Debian) OpenSSL/1.1.1w configured -- resuming normal operations
[Tue Sep 24 00:00:10.257353 2024] [core:notice] [pid 291142:tid 291142] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 24 00:05:06.491503 2024] [proxy_fcgi:error] [pid 585804:tid 585861] [client 94.156.65.250:50240] AH01071: Got error 'Primary script unknown'
[Tue Sep 24 00:06:58.333693 2024] [proxy_fcgi:error] [pid 585803:tid 585889] [client 94.156.65.250:60752] AH01071: Got error 'Primary script unknown'
[Tue Sep 24 00:39:47.704524 2024] [proxy_fcgi:error] [pid 585804:tid 585866] [client 134.209.174.139:40424] AH01071: Got error 'Primary script unknown'
[Tue Sep 24 00:56:15.664730 2024] [proxy_fcgi:error] [pid 585803:tid 585834] [remote 57.141.0.24:41552] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "WP_Widget" not found in /var/www/html/wordpress/wp-content/themes/Band/includes/widgets/my-comment-widget.php:3\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-content/themes/Band/includes/widgets/my-comment-widget.php on line 3'
[Tue Sep 24 14:41:54.121262 2024] [authz_core:error] [pid 585803:tid 585888] [client 20.204.154.50:55049] AH01630: client denied by server configuration: /var/www/html/wordpress/wp-content/uploads/wpcf7_uploads/, referer: binance.com
[Tue Sep 24 14:45:50.957643 2024] [proxy_fcgi:error] [pid 585803:tid 585891] [client 20.204.154.50:59789] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "ABSPATH" in /var/www/html/wordpress/wp-includes/class-wp-http.php:11\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/class-wp-http.php on line 11', referer: binance.com
[Tue Sep 24 14:46:23.889392 2024] [proxy_fcgi:error] [pid 585803:tid 585907] [client 20.204.154.50:65350] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "WP_Dependencies" not found in /var/www/html/wordpress/wp-includes/class-wp-scripts.php:18\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/class-wp-scripts.php on line 18', referer: binance.com
[Tue Sep 24 14:46:29.080886 2024] [proxy_fcgi:error] [pid 585803:tid 585894] [client 20.204.154.50:50122] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "WP_Dependencies" not found in /var/www/html/wordpress/wp-includes/class-wp-styles.php:18\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/class-wp-styles.php on line 18', referer: binance.com
[Tue Sep 24 14:47:48.578034 2024] [proxy_fcgi:error] [pid 585803:tid 585898] [client 20.204.154.50:52351] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_the_block_template_html() in /var/www/html/wordpress/wp-includes/template-canvas.php:12\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/template-canvas.php on line 12', referer: binance.com
[Tue Sep 24 14:49:20.807732 2024] [proxy_fcgi:error] [pid 585803:tid 585898] [client 20.204.154.50:57749] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "ABSPATH" in /var/www/html/wordpress/wp-includes/blocks/index.php:8\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/blocks/index.php on line 8', referer: binance.com
[Tue Sep 24 14:50:09.709716 2024] [proxy_fcgi:error] [pid 585804:tid 585876] [client 20.204.154.50:53009] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "WP_Widget" not found in /var/www/html/wordpress/wp-includes/widgets/class-wp-widget-block.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/html/wordpress/wp-includes/widgets/class-wp-widget-block.php on line 17', referer: binance.com
[Tue Sep 24 16:01:11.215288 2024] [core:error] [pid 585803:tid 585890] [client 8.217.215.71:34072] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Tue Sep 24 16:01:14.972969 2024] [core:error] [pid 585803:tid 585894] [client 8.217.215.71:34462] AH10244: invalid URI path (/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
```

### Log file

```Text
The requested uri(/apps/tasks/css/tasks-store.css) cannot be processed by the script '/nextcloud/index.php')
```

**Comment by hanneschu1z** [comment] 2024-09-24 16:02
I already run:
sudo chown -R www-data:www-data /path/to/nextcloud/apps/tasks/css/
sudo chmod -R 755 /path/to/nextcloud/apps/tasks/css/

I update everything and reinstalled tasks.

The file seems to be missing:
![image](https://github.com/user-attachments/assets/a71f54f0-0f74-4d7c-a180-e1d3f1431273)

**Comment by raimund-schluessler** [comment] 2024-09-24 20:40
Duplicate of #2665. It will be fixed by the next release. Until then you can just ignore it.

**Closed** 2024-09-24 20:41 UTC
Labels: bug
