### ISSUE TITLE
Sub-tasks not shown in "Today" pane

### ISSUE THREAD

**Issue by SwissTico** [nextcloud/tasks#500] opened 2019-07-11 17:49 UTC
### Steps to reproduce
1. Create a task
2. Create a sub-task
3. Add a due date for today to the subtask (without adding main task due date)
4. Go to "Today" or "This week" pane on the left

### Expected behaviour
The sub-task with the due date is not shown in the list.

### Actual behaviour
The sub-task should be shown in the list.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
16.0.3

**Tasks version:** (see Nextcloud apps page)
 0.11.0

**Updated from an older Nextcloud or fresh install:**
Updated

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration

**Browser:**
Firefox 68

**Comment by raimund-schluessler** [comment] 2019-07-11 18:15
Duplicate of #83, will be fixed with #431.

**Closed by raimund-schluessler** 2019-07-11 18:15 UTC
