### ISSUE TITLE
On mobile view you cannot scroll down

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#457] opened 2019-06-23 10:55 UTC
### Steps to reproduce
1. Install the Task app from the app store, open it and create a few tasks.
2. Login on my mobile phone with the "Brave" browser (which is based on Chromium).
3. Now I try to scroll down.

### Expected behaviour
Should be able to scroll down.

### Actual behaviour
Not able to scroll down because the task I am currently touching is just moved.

## Server configuration detail

**Operating system:** Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.26

**PHP version:** 

7.2.19
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 16.0.2 RC1 - 16.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.0.8

**Where did you install Nextcloud from:** Snap Store

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bookmarks: 1.0.6
 - calendar: 1.7.0
 - circles: 0.17.4
 - cloud_federation_api: 0.2.0
 - contacts: 3.1.3
 - cospend: 0.1.0
 - dav: 1.9.2
 - deck: 0.6.4
 - drawio: 0.9.3
 - event_update_notification: 0.3.4
 - external: 3.3.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_3d: 0.1.0
 - files_downloadactivity: 1.5.0
 - files_ebookreader: 0.0.1
 - files_external: 1.7.0
 - files_linkeditor: 1.0.10
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - guests: 1.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.6.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quickaccesssorting: 1.0.1
 - radio: 0.6.5
 - rainloop: 6.0.2
 - ransomware_detection: 0.5.2
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharerenamer: 2.6.0
 - spreed: 6.0.2
 - suspicious_login: 1.0.0
 - tasks: 0.11.0
 - telephoneprovider: 1.0.2
 - text: 1.0.0
 - theming: 1.7.0
 - twofactor_admin: 0.4.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.1
 - twofactor_totp: 2.1.2
 - video_converter: 0.1.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - comments
 - encryption
 - federation
 - files_texteditor
 - sharebymail
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.2.0",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "465",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "disabled",
    "loglevel": 2,
    "share_folder": "\/Shared",
    "preview_max_x": 1536,
    "preview_max_y": 1536,
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG"
    ],
    "app_install_overwrite": [
        "occweb"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** Local cifs-utils

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Linux; Android 9; SM-G970F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36

**Operating system:** Android P

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by raimund-schluessler** [comment] 2019-06-23 13:58
Duplicate of #421.

**Comment by szaimen** [comment] 2019-07-02 13:26
Thank your for referencing. The thing is, that this issue should get fixed with version 0.11 and I am already running this version on my nextcloud but it also does not work with this version.
So please reopen the issue.

**Comment by raimund-schluessler** [comment] 2019-07-02 15:04
@szaimen Please make sure you don't use a cached version of the app. Clear the cache of your mobile browser and reload the Tasks app.

It works fine for me with Safari on iOS12. We use a delay of 500 ms. After you touched a tasks longer than this time without moving your finger the dragging starts.

If the issue really persists for you, please fill the complete issue template. Otherwise I won't be able to reproduce your problem.

**Comment by szaimen** [comment] 2019-07-02 17:04
Done!

**Comment by raimund-schluessler** [comment] 2019-07-02 19:44
@szaimen Thanks for filling the issue template.

I tested again on iOS12 with three different browsers (Mobile Safari, Chrome and Firefox) and it works well for all of them. However, on a borrowed Android device (Samsung A3, don't know which Android version it runs, probably a really old one) I can reproduce your issue. Dragging sometimes starts, sometimes it kinda works.

However, this is an upstream issue in the drag-and-drop library we use (Vue.Draggable, which itself uses Sortable.js). So we cannot fix it ourselves directly. There recently was a fix https://github.com/SortableJS/Sortable/issues/1517 for the delay option in relation with Android, so it might be fixed with one of the next releases of Vue.Draggable.

**Comment by raimund-schluessler** [comment] 2019-07-03 09:16
@szaimen Could you please check that the issue also occurs on this minimal example: https://codepen.io/raimund-schluessler/pen/EBRxdz
I would like to report it upstream to Sortable.js.

**Comment by szaimen** [comment] 2019-07-03 11:19
Yeah, I tested your example and the issue also occurs there - every time.

**Comment by szaimen** [comment] 2019-07-03 11:20
Thank you for reopen!

**Comment by raimund-schluessler** [comment] 2019-07-03 19:09
I reported the issue in https://github.com/SortableJS/Sortable/issues/1556

**Comment by szaimen** [comment] 2019-07-03 22:04
Thanks!

**Comment by raimund-schluessler** [comment] 2019-07-05 12:38
The issue should be fixed upstream now, but it will take some time until updated releases of the libraries are published.

**Comment by szaimen** [comment] 2019-09-15 19:46
@raimund-schluessler the Sortable.js-upsate is finally out :+1:

**Comment by raimund-schluessler** [comment] 2019-09-15 19:55
> @raimund-schluessler the Sortable.js-upsate is finally out 👍

That's good. I will check if we can already use it, or if we have to wait for Vuedraggable.

**Closed** 2019-09-16 12:02 UTC
Labels: bug, upstream

**Comment by raimund-schluessler** [comment] 2019-09-16 12:04
Should be fixed in master now. I will release 0.11.3 once I was able to test if the problem is solved (I don't have access to an android device atm).

**Comment by raimund-schluessler** [comment] 2019-09-17 18:10
0.11.3 is out now.

**Comment by szaimen** [comment] 2019-09-17 18:24
Nice! Thank you! It is working now! 🎉
