### ISSUE TITLE
dark theme and task

### ISSUE THREAD

**Issue by Niouby** [nextcloud/tasks#265] opened 2019-02-11 09:47 UTC
Hi,

Thank you to propose an official dark theme on Nextcloud. I'm on Nextcloud 15.0.4 with Tasks
0.9.8 .
But I have some issues on the task app, some elements remained with the white background, like all the tasks in the middle panel

Here is an example : 
![image](https://user-images.githubusercontent.com/3193898/52555303-97dd3f80-2de9-11e9-8f5a-5eac17fc3343.png)

Sorry but I don't know if I have to create this issue on the Task app repository (https://github.com/nextcloud/tasks/issues) or here.

**Comment by raimund-schluessler** [comment] 2019-02-11 15:30
Thanks for the report, but it is a duplicate of https://github.com/nextcloud/tasks/issues/218 which was fixed with #219.

You can expect a working dark theme support for Tasks in the next version. Please see https://github.com/nextcloud/tasks/milestone/1 for what is left to do until the release.

**Closed by raimund-schluessler** 2019-02-11 15:30 UTC

**Comment by Niouby** [comment] 2019-02-12 09:02
Perfect !
Thank you very much and have a nice day.
