### ISSUE TITLE
[Feature request] Allow sort lists by name or position

### ISSUE THREAD

**Issue by ffuentes** [nextcloud/tasks#347] opened 2019-04-02 15:12 UTC
### Steps to reproduce
1. Create a bunch of list
2. Try to order lists by drag & drop
3. Try to order lists by name

### Expected behaviour
Allow the user to order lists by name or by position.

### Actual behaviour
Lists are sorted by created date.

**Nextcloud version:** 15.0.5
**Tasks version:** 0.9.8

**Comment by raimund-schluessler** [comment] 2019-04-02 15:26
Duplicate of https://github.com/nextcloud/tasks/issues/15

**Closed by raimund-schluessler** 2019-04-02 15:26 UTC
