### ISSUE TITLE
[Feature Request] printing or formatted export

### ISSUE THREAD

**Issue by GregorB54321** [nextcloud/tasks#1307] opened 2020-10-25 11:18 UTC
Dear developer!

I'm using your charming application since years. But I  ever missed the opportunity to have my huge list (200 lines) printed at refrigerator. :-)
I don't know how complicated printing is to implement. Printing via firefox's print function does not gives acceptable output. It seems to be limited to 5 pages with tasks, remaining pages don't contain the tasks but all other website-content. Also the text of the tasks seems to be printed as compressed graphics -> unreadable when printed page also needs to be scaled down.

But maybe it would be easier to implement export function? When I mark all and copy/paste it into Libre/OpenOffice Writer / MS Word I don't get correctly indented format for subtasks. It would be helpful, If it would be indented by leading tabulator or spaces.
Thanks a lot in advance!

BR, Gregor

**Comment by raimund-schluessler** [comment] 2020-10-28 11:16
Duplicate of #74 (for the printing part) and #163 (for the excel export).

**Closed by raimund-schluessler** 2020-10-28 11:16 UTC
