### ISSUE TITLE
userID being used when sharing instead of displayName or FullName

### ISSUE THREAD

**Issue by meichthys** [nextcloud/tasks#1738] opened 2021-08-02 20:58 UTC
**Describe the bug**
userID instead of the displayName or FullName is being used when sharing task lists:
![image](https://user-images.githubusercontent.com/10717998/127922454-194549ec-f16d-4d88-93cd-489b6a663f23.png)
For reference, the calendar app seems to use the displayName/fullName:
![image](https://user-images.githubusercontent.com/10717998/127922649-358bb610-4f99-4a4c-bb70-677af2a6673d.png)

I might be wrong, but I think the userID is [ intended to not be user-facing](https://github.com/nextcloud/server/issues/21762#issuecomment-662333077). A few other fixed bugs in other apps seem to have replaced the userID with a displayName or FullName ( #43, #74 ), however the userID still appears to be used by the Tasks app when sharing.

In some cases this probably isn't much of an issue since the userID may be human readable, but when using integrations like LDAP, the unchangeable userID looks quite ugly.

**To Reproduce**
1. Go to Tasks app
2. Try to share a task list
3. Search for a user _name_ to share
4. See error: The listed userID(s) will be displayed (often an ugly uuid when using LDAP) instead of showing displayName or Full Name.

**Expected behavior**
I would expect the search to show the displayName or FullName of the user i would like to share with, rather than the userID which is not changeable or readable.

**Client details:**
 - OS: Windows 10
 - Browser: Firefox (also tested with other browsers)
 - Version: 22
 - Device: Desktop

**Comment by raimund-schluessler** [comment] 2021-08-02 21:08
This seems like a duplicate of #1721 which was fixed with Tasks v0.14.1 (released a few minutes ago).

I guess you are still on v0.14.0 or earlier, so please update to the latest version.

**Closed by raimund-schluessler** 2021-08-02 21:08 UTC

**Comment by meichthys** [comment] 2021-08-03 11:53
Sure Enough! Thanks!
![image](https://user-images.githubusercontent.com/10717998/128010835-5a380c8f-ee13-455f-a6c9-924f58dd2e5e.png)
